cloudposse/terraform-aws-components

Dockerfile, codefresh.yml
* Publish images to Docker Hub
* Use scratch image
* simplify documentation to allow others to include our public root modules in their geodesic modules
=> Push stable images to dockerhub

codefresh.yml
* Push to `cloudposse/terraform-root-modules`
* Without specifying `image_name` it defaults to `library` which is owned by docker.
=> Push to `cloudposse` Registry

aws/organization/main.tf, aws/organization/terraform.tfvars.example
* Add `organization` project
* To easily create an AWS Organization from the master account
=> Add `organization` project

README.md, aws/accounts/testing.auto.tfvars.example, aws/accounts/testing.tf, aws/iam/testing.auto.tfvars.example, aws/iam/testing.tf
* Add projects for `testing` stage
* To have an account to quickly create and destroy infrastructure for testing
=> Add `testing` stage

aws/kops-aws-platform/chart-repo.tf, aws/kops-aws-platform/main.tf
* Make configurable what servers can assume role `masters`, `nodes` or `both`
* For `kiam` we need just `masters`, for `kube2iam` just `nodes`
=> Feature fix chart repo

aws/chamber/main.tf, aws/chamber/user.tf
* Grant chamber permissions for `app` secrets group
* We use pattern `chamber exec kops app` so need access to both
=> Grant premissions for app secrets group

aws/backing-services/elasticsearch.tf
* Name `Elasticsearch` variable
* `Elastic search` domain name limited to 23 chars max, so we need to allow make name less
=> Make elasticsearch name variable

aws/backing-services/elasticsearch.tf
* Allow to provide `any` role access to `ElasticSearch`
* Portal 2 can not assume role to access kibana, because we use k8s service[type=externalName]
=> Added elasticsearch permissions

aws/backing-services/elasticsearch.tf, aws/backing-services/rds.tf
* Added RDS as backing service
* To make it useful for some projects
=> Added rds as backing service

aws/backing-services/aurora-mysql.tf
* Add `allowed_cidr_blocks` to `aurora-mysql`
* To make it publicly accessible
For an Aurora cluster to be publicly accessible, the following three conditions must be met:
1. `publicly_accessible` flag must be set to `true`, in which case the RDS instances will be assigned a public IP address and the internal DNS will be pointed to it (otherwise it will be assigned a private IP address)
2. The instances must be placed into public subnets (with an Internet Gateway), so they could be reached from the Internet
3. The Security Group must have ingress rules to allow connection from an external IP address, CIDR blocks, or other security groups. To allow public access from any IP, use `"0.0.0.0/0"` as allowed CIDR blocks
=> Add `allowed_cidr_blocks` to `aurora-mysql` to make it publicly accessible

aws/accounts/audit.auto.tfvars.example, aws/accounts/audit.tf, aws/accounts/corp.tf, aws/accounts/data.tf, aws/accounts/dev.auto.tfvars.example, aws/accounts/dev.tf, aws/accounts/identity.tf, aws/accounts/main.tf, aws/accounts/prod.auto.tfvars.example, aws/accounts/prod.tf, aws/accounts/security.tf, aws/accounts/staging.auto.tfvars.example, aws/accounts/staging.tf, aws/accounts/testing.auto.tfvars.example, aws/accounts/testing.tf
* Enforce that a common format is used for all emails (`e.g. ops+%s@example.co`)
* Add some additional accounts for other use-cases
* Provide a stable way to enable/disable accounts
* Eliminate nearly all variables to reduce customization burden
* Simplifying the cold start problem
* Using `counts` is not a "stable" way to allocate stateful resources like accounts
=> [accounts] Enforce consistent email convention and add new accounts

aws/iam/audit.auto.tfvars.example, aws/iam/audit.tf, aws/iam/corp.tf, aws/iam/data.tf, aws/iam/dev.auto.tfvars.example, aws/iam/dev.tf, aws/iam/identity.tf, aws/iam/main.tf, aws/iam/prod.auto.tfvars.example, aws/iam/prod.tf, aws/iam/security.tf, aws/iam/staging.auto.tfvars.example, aws/iam/staging.tf, aws/iam/testing.auto.tfvars.example, aws/iam/testing.tf, aws/iam/variables.tf
Use account remote state to fetch sub account IDs. This should resolve https://github.com/cloudposse/terraform-root-modules/issues/62
So that we don’t need to hardcode these as vars e.g. in the top root [Dockerfile](https://github.com/cloudposse/root.cloudposse.co/blob/master/Dockerfile#L25)
I have tested this locally by rebuilding `terraform-root-modules`, pulling that into `root.cloudposse.co` Geodesic and running an IAM plan, which was a no-op:
```
✓   (cpco-root-admin) iam ⨠  terraform plan
Acquiring state lock. This may take a few moments...
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.
data.terraform_remote_state.accounts: Refreshing state... …
```
=> [iam] Use account remote state to fetch sub account IDs

aws/accounts/Makefile, aws/accounts/audit.tf, aws/accounts/corp.tf, aws/accounts/data.tf, aws/accounts/dev.tf, aws/accounts/identity.tf, aws/accounts/main.tf, aws/accounts/prod.tf, aws/accounts/security.tf, aws/accounts/staging.tf, aws/accounts/testing.tf
* Publish AWS Account details to SSM parameter store
* With SSM parameter store, we can reference parameters using the variable names in other modules, which makes it easier to query data programmatically since we don't need to hardcode attributes.
=> [aws/accounts] Publish account details to SSM

aws/organization/Makefile, aws/tfstate-backend/Makefile, aws/users/Makefile, aws/users/variables.tf
* Add `Makefile` to `aws/organizations`
* Support `make init` in `tfstate-backend` when backend already provisioned
* Make `SMTP_*` vars optional (only needed if sending mail and we're not always going to be doing that)
* Use `Makefile` as the standard interface for all root modules => consistency & documentation
* https://github.com/cloudposse/reference-architectures/pull/1
=> Fixes for reference-architectures

aws/accounts/audit.tf, aws/accounts/corp.tf, aws/accounts/data.tf, aws/accounts/dev.tf, aws/accounts/identity.tf, aws/accounts/prod.tf, aws/accounts/security.tf, aws/accounts/stage/main.tf, aws/accounts/stage/outputs.tf, aws/accounts/stage/variables.tf, aws/accounts/staging.tf, aws/accounts/testing.tf
* Define `aws_ssm_parameter` parameters directly rather than rely on ssm module
* Use a submodule to reduce copy/pasta mistakes
* `value of 'count' cannot be computed` errors
* Do not want to update `terraform-aws-ssm-parameter-store` to pass in count explicitly (no added benefit at this point)
* You'll need to migrate the state for accounts to the submodule
```
terraform state mv aws_organizations_account.audit  module.audit.aws_organizations_account.default
terraform state mv aws_organizations_account.staging  module.staging.aws_organizations_account.default
```
=> [aws/accounts] do not use ssm module

aws/users/main.tf
* Add `signin_url` output
* Make it easier to "copy and paste" login information =)
=> [aws/users] Add signin url output

aws/iam/audit.tf, aws/iam/corp.tf, aws/iam/data.tf, aws/iam/dev.tf, aws/iam/identity.tf, aws/iam/prod.tf, aws/iam/security.tf, aws/iam/staging.tf, aws/iam/testing.tf, aws/root-iam/main.tf, aws/root-iam/root.tf, aws/root-iam/variables.tf, aws/users/main.tf, aws/users/variables.tf
* Write admin/readonly groups to SSM
* Use groups from SSM to determine membership for `admin_groups`
* Support a dynamic list of admin groups for an arbitrary number of AWS accounts
=> [users] dynamic account groups

aws/users/main.tf
* Added `root` to list of accounts enabled
* It's implicit, so it wasn't included in the `accounts_enabled` flag.
* https://github.com/cloudposse/terraform-root-modules/pull/74
=> Include default account of root as enabled

aws/backing-services/aurora-postgres.tf, aws/backing-services/elasticache-redis.tf, aws/backing-services/elasticsearch.tf, aws/backing-services/kops-metadata.tf
* Ensure all backing services have flags
* Default flags to false
* The default state should be disabled for everything, so we explicitly enable services
To maintain backwards compatibility, create a `terraform.tfvars` file with the following content:
```
postgres_cluster_enabled = "true"
redis_cluster_enabled = "true"
elasticsearch_enabled = "true"
kops_metadata_enabled = "true"
```
=> [backing-services] Add flags, change defaults to false

aws/kops/Makefile, aws/kops/README.md, aws/kops/main.tf, aws/kops/variables.tf
* Add a `README.md` to roughly describe the process
* Add some **simple** targets that are common when provisioning a new cluster
* The `Makefile` targets serve as *executable documentation*; that is, they can be copied & pasted just as easily as they can be run. They are not difficult to understand.
* This makes writing the documentation easier that pasting commands into the `README.md` which will just grow stale.
=> [kops] Add targets and README.md

README.md, README.yaml, aws/account-dns/Makefile, aws/account-settings/Makefile, aws/accounts/Makefile, aws/acm-cloudfront/Makefile, aws/acm/Makefile, aws/artifacts/Makefile, aws/audit-cloudtrail/Makefile, aws/backing-services/Makefile, aws/bootstrap/Makefile, aws/chamber/Makefile, aws/cloudtrail/Makefile, aws/docs/Makefile, aws/ecr/Makefile, aws/eks-backing-services-peering/Makefile, aws/eks/Makefile, aws/iam/Makefile, aws/kops-aws-platform/Makefile, aws/kops/Makefile, aws/organization/Makefile, aws/root-dns/Makefile, aws/root-iam/Makefile, aws/ses/Makefile, aws/tfstate-backend/Makefile, aws/users/Makefile, aws/vpc-peering/Makefile
* Update all `Makefiles` to have an include
* When importing the root modules into accounts, it's convenient to have multiple makefiles
* Allow inheriters to define `Makefile.something` where `something` can be anything =)
=> [*/Makefile] include `Makefile.*`

README.md, README.yaml, aws/account-dns/Makefile, aws/account-settings/Makefile, aws/accounts/Makefile, aws/acm-cloudfront/Makefile, aws/acm/Makefile, aws/artifacts/Makefile, aws/audit-cloudtrail/Makefile, aws/backing-services/Makefile, aws/bootstrap/Makefile, aws/chamber/Makefile, aws/cloudtrail/Makefile, aws/docs/Makefile, aws/ecr/Makefile, aws/eks-backing-services-peering/Makefile, aws/eks/Makefile, aws/iam/Makefile, aws/kops-aws-platform/Makefile, aws/kops/Makefile, aws/organization/Makefile, aws/root-dns/Makefile, aws/root-iam/Makefile, aws/ses/Makefile, aws/tfstate-backend/Makefile, aws/tfstate-backend/scripts/destroy.sh, aws/tfstate-backend/scripts/init.sh, aws/users/Makefile, aws/vpc-peering/Makefile
* Remove `include Makefile.*` as it caused some problems [this pr](https://github.com/cloudposse/geodesic/pull/354) and introduced in #92.
* Remove remaining references to `init-terraform` since we can achieve the same thing using `tfenv`
* Part of the refactoring to better support `terraform init -from-module=...`
=> Remove references to init-terraform

aws/ecs/atlantis.tf
* Allow container limits to be overridden
* When too little CPU is given to `terraform`, we see random `EOF` errors
=> [aws/ecs] atlantis container limits

aws/kops-aws-platform/efs-provisioner.tf
Creates an IAM role with EFS permissions
This IAM role will be used to annotate the efs-provisioner helmfile so
that we can mount EFS volumes into our k8s clusters.
=> Add kops efs-provisioner IAM role

aws/kops/Makefile, aws/kops/main.tf, aws/kops/outputs.tf
* Write kops keys to SSM
* Writing to disks makes it hard b/c we don't have `goofys` in the ECS task and local filesystems won't be reliable with atlantis running on an ephemeral disk
=> [aws/kops] Use SSH keys from SSM

aws/kops/main.tf, aws/kops/variables.tf
* Reduce default key size
* SSM Parameter store has a max limit of `4096` bytes.
=> [aws/kops] Reduce default ssh key size

aws/backing-services/vpc.tf, aws/codefresh-onprem/kops-metadata.tf, aws/codefresh-onprem/main.tf
PR to add CodeFresh Enterprise backing services to terraform-root-modules
so we can provision these CodeFresh Enterprise backing services into the backing service VPC and subnets.
Note that I have had to add some new outputs to the `backing-services` module so that I can import these as remote state to pass into the `terraform-aws-codefresh-backing-services` module
=> [aws/codefresh-onprem] Add Enterprise backing services

aws/codefresh-onprem/Makefile
This adds the standard makefile to codefresh-onprem
So Atlantis can plan / apply steps using the makefile wrapper.
=> Add standard makefile for codefresh-onprem

aws/codefresh-onprem/main.tf
I was wondering what was going on here when applying codefresh-onprem
via Atlantis and getting unexpected SSM param prefixes 
e.g. `/21ba4b10dd0ca831a7458b77c31ee2f6/aurora_postgres_cluster_name`
at which point I realised that Atlantis runs in a scratch directory so
we need to explicitly set `chamber_service` to stop it defaulting to
the scratch directory when running under Atlantis. This will likely bite
us anyplace we do as [1] and run terraform via Atlantis.
[1] https://github.com/cloudposse/terraform-aws-codefresh-backing-services/blob/master/main.tf#L98
From: 
```terraform
-/+ module.codefresh_enterprise_backing_services.aws_ssm_parameter.s3_user_iam_secret_access_key (new resource required)
id:          "/21ba4b10dd0ca831a7458b77c31ee2f6/aws_secret_access_key" => <computed> (forces …
```
=> Explicitly set codefresh_onprem chamber_service

aws/backing-services/elasticsearch.tf
Fix role_arns local variable
This local variable was renamed in 99cf52e but this was missed and is
causing Terraform to fail.
```
Error: module.elasticsearch.var.iam_role_arns: local.arns: no local value of this name has been declared
```
=> Fix role_arns local variable

aws/codefresh-onprem/main.tf
Surfaces codefresh-onprem outputs to the caller module
So we correctly output codefresh-onprem outputs
Running the thing for `corp.even.co`:
```
Outputs:
aurora_postgres_cluster_name = <redacted>
aurora_postgres_database_name = <redacted>
aurora_postgres_master_hostname = <redacted>
aurora_postgres_master_username = <redacted>
aurora_postgres_replicas_hostname = <redacted>
elasticache_redis_host = <redacted>
elasticache_redis_id = <redacted>
elasticache_redis_security_group_id = <redacted>
s3_access_key_id = <sensitive>
s3_bucket_arn = <redacted>
s3_secret_access_key = <sensitive>
s3_user_arn = <redacted>
s3_user_name = <redacted>
s3_user_unique_id = <sensitive>
```
Note that I have redacted all outputs in this PR, not that that these things are particularly sensitive.
=> Surface codefresh-onprem outputs

aws/iam/audit.tf, aws/iam/corp.tf, aws/iam/data.tf, aws/iam/dev.tf, aws/iam/identity.tf, aws/iam/prod.tf, aws/iam/security.tf, aws/iam/staging.tf, aws/iam/testing.tf
Bump aws-organization-access-group to 0.4.0
To pull in https://github.com/cloudposse/terraform-aws-organization-access-group/releases/tag/0.4.0 fixes
=> Bump aws-organization-access-group to 0.4.0

aws/kops-aws-platform/iam-authenticator.tf, aws/kops-aws-platform/main.tf, aws/kops-iam-users/corp.tf, aws/kops-iam-users/data.tf, aws/kops-iam-users/dev.tf, aws/kops-iam-users/main.tf, aws/kops-iam-users/prod.tf, aws/kops-iam-users/staging.tf, aws/kops-iam-users/testing.tf, aws/kops-iam-users/variables.tf
Adds terraform-aws-kops-iam-authenticator-config module to terraform-root-modules so we can write a configMap for `aws-iam-authenticator` to our kops clusters. 
It also adds kubernetes admin (default: `KubernetesAdmin`) and readonly (default: `KubernetesReadOnly`) IAM groups and associated IAM roles (no policy required) to our root AWS account allowing sub accounts to assume the role.
* Fine grained access controls to Kubernetes 
See https://github.com/kubernetes-sigs/aws-iam-authenticator#full-configuration-format
=> Add Kops IAM authenticator

aws/kops-iam-users/corp.tf, aws/kops-iam-users/data.tf, aws/kops-iam-users/dev.tf, aws/kops-iam-users/prod.tf, aws/kops-iam-users/staging.tf, aws/kops-iam-users/testing.tf
Bump org access group to 0.4.0
To pull in the IAM group membership fix
=> Bump org access group to 0.4.0

aws/kops-iam-users/corp.tf, aws/kops-iam-users/data.tf, aws/kops-iam-users/dev.tf, aws/kops-iam-users/main.tf, aws/kops-iam-users/prod.tf, aws/kops-iam-users/staging.tf, aws/kops-iam-users/testing.tf
Have a module per account for `kops-iam-users`
Otherwise we are passing the wrong stage e.g. root, when it should be
testing for this role.
=> Label per account

aws/datadog/Makefile, aws/datadog/main.tf, aws/datadog/terraform.tfvars.example, aws/datadog/variables.tf
* Add IAM role required by Datadog for AWS integration
* Use SSM Parameter store retrieve External ID
* To support the Datadog official integration with AWS
* https://docs.datadoghq.com/integrations/amazon_web_services/
Requires [terraform-aws-datadog-integration PR 8](https://github.com/cloudposse/terraform-aws-datadog-integration/pull/8) version 0.2.0
=> Add Datadog provisioning

aws/ecs/dns.tf
* Explicitly set `allow_overwrite=true` via https://github.com/cloudposse/terraform-aws-route53-cluster-zone/pull/19
* This is required to set the `SOA` for a zone, which will be created automatically by AWS
* Functionality changed in the latest `terraform-aws-provider`
* https://www.terraform.io/docs/providers/aws/guides/version-2-upgrade.html#allow_overwrite-default-value-change
* https://github.com/terraform-providers/terraform-provider-aws/issues/7846
=> [aws/ecs] Fix `allow_overwrite` for SOA

aws/kops-aws-platform/iam-authenticator.tf
Add a "view" group to Kubernetes for the read-only IAM role 
Kubernetes has a default ClusterRole called `view` but it is not bound to anything. By creating a binding to a group named `view` we can give the read-only IAM role this ClusterRole, which is a default Kubernetes ClusterRole designed for read-only viewers.
=> [kops-aws-platform] Add "view" role to k8s

aws/kops-aws-platform/alb-ingress.tf
* Support renamed terraform module `terraform-aws-kops-aws-alb-ingress`
* To fix bug
=> [aws/kops-aws-platform] Update alb terraform module

aws/account-settings/main.tf, aws/account-settings/outputs.tf, aws/account-settings/variables.tf
Adding a new variable `minimum_password_length` to the `aws/account-settings` module.
Account settings should write and output the account-level minimum password lengths so that
our https://github.com/cloudposse/terraform-aws-iam-user module can use the output value when createing users, so valid password lengths can be used.
=> [aws/account-settings] add var to module: minimum_password_length

aws/teleport/main.tf
User HTTPS rather than git: to retrieve modules
Does not require authentication
=> [teleport] Use public access to repo

aws/kops-aws-platform/iam-authenticator.tf, aws/teleport/main.tf
Disable kops iam integration by default
Most users do not want kops iam integration, but prior to this change, it was forced on them.
=> [kops-aws-platform] Disable kops-iam by default

aws/kops/Makefile
Add `kops/replace` target form `make`
When updating a cluster with a new configuration, you need to use `replace` instead of `update`
=> [kops] Add kops/replace target

aws/account-dns/main.tf
Because of [changes to the terraform aws provider](https://www.terraform.io/docs/providers/aws/guides/version-2-upgrade.html#allow_overwrite-default-value-change), the account-dns module needs to be updated to allow for overwriting the SOA dns record.
=> [aws/account-dns] Add allow_override for SOA record

LICENSE, aws/ecs/README.md, aws/ecs/atlantis.auto.tfvars.example, aws/ecs/atlantis.tf, aws/ecs/default-backend.tf
* Add `Cognito` and `OIDC` authentication to ECS for Atlantis
* To be able to authenticate Atlantis ALB endpoints with Cognito or OIDC (e.g. Google, GitHub)
=> [ecs/atlantis] Add `Cognito` and `OIDC` authentication

aws/root-dns/parent.tf, aws/root-dns/root.tf
[root-dns] Update to work with Terraform AWS provider version 2.0
Version 2.0 introduced a breaking change that broke `root-dns`. This fixes it.
=> [root-dns] Update to work with Terraform AWS provider version 2.0

aws/codefresh-onprem/main.tf
* [codefresh-onprem] Add DocumentDB cluster
* Provision Amazon DocumentDB for Codefresh Enterprise and use it instead of MongoDB
=> [codefresh-onprem] Add DocumentDB cluster

aws/kops-aws-platform/variables.tf, aws/kops-aws-platform/vpc-peering.tf, aws/kops/Makefile, aws/kops/main.tf, aws/kops/outputs.tf, aws/kops/variables.tf, aws/vpc/Makefile, aws/vpc/main.tf, aws/vpc/outputs.tf, aws/vpc/variables.tf
New `vpc` module creates these parameters in `chamber vpc`:
```
vpc_common_availability_zones
vpc_common_cidr_block	
vpc_common_igw_id	
vpc_common_nat_gateways	
vpc_common_private_subnet_cidrs
vpc_common_private_subnet_ids
vpc_common_public_subnet_cidrs
vpc_common_public_subnet_ids
vpc_common_vpc_id	
```
Tag labels are like (for example, for a subnet in one AZ) `cpco-prod-vpc-common-us-west-2a`
Updated [kops] module imports VPC made by new [vpc] module. Depends on `kops-private-topology.yaml.gotmpl` from https://github.com/cloudposse/reference-architectures/releases/tag/0.7.0
Make it easier to add additional services to the same VPC kubernetes is using.
=> [vpc][kops]Create VPC by itself and have kops adopt it

aws/kops-legacy-account-vpc-peering/Makefile, aws/kops-legacy-account-vpc-peering/README.md, aws/kops-legacy-account-vpc-peering/main.tf, aws/kops-legacy-account-vpc-peering/outputs.tf, aws/kops-legacy-account-vpc-peering/terraform.tfvars.example, aws/kops-legacy-account-vpc-peering/variables.tf
* Add `kops-legacy-account-vpc-peering` project
* Provision VPC peering connection between a `kops` VPC and a legacy VPC in a different AWS account (possibly provisioned manually without using Terraform or other automation tools)
* Specify what parameters are needed from the legacy AWS account to be able to provision a VPC peering connection
* Show the IAM role, policies and permissions required in the legacy account
=> Add [kops-legacy-account-vpc-peering]

README.md, aws/codefresh-onprem/main.tf
* Bump `terraform-aws-codefresh-backing-services` version
* https://github.com/cloudposse/terraform-aws-rds-cluster/pull/49
* https://github.com/cloudposse/terraform-aws-documentdb-cluster/pull/3
* https://github.com/cloudposse/terraform-aws-codefresh-backing-services/pull/5
=> Bump `terraform-aws-codefresh-backing-services` version

aws/codefresh-onprem/main.tf
* Disable TLS for document DB
* Codefresh does not support TLS  connection to MongoDB
=> Disable TLS by default

aws/acm-teleport/Makefile, aws/acm-teleport/main.tf, aws/acm-teleport/outputs.tf, aws/acm-teleport/terraform.tfvars.example, aws/acm-teleport/variables.tf, aws/teleport/main.tf
- [teleport] Update teleport module to work in shared VPC
- [acm-teleport] Create teleport-specific module for generating Teleport TLS certificate via ACM
More automation of Teleport install process.
=> [teleport] Update teleport module to work in shared VPC, add acm-teleport module

aws/backing-services/vpc.tf
* Added `vpc_max_subnets_count`
* Allow specifying the count of ranges CIDR is split to
=> [backing services] Fix CIDR range because of new availability zone

aws/ecs/atlantis.tf, aws/ecs/default-backend.tf
* Fix authentication action
* Don't use `map` variable for authentication action
* Using `authentication_action` variable as `map` breaks when this module is used in a chain of calls from other modules
For example:
* Providing `authentication_action` map from Module B to `alb-ingress` - works
* Providing `authentication_action` map from Module C to Module B to `alb-ingress` - works
* Providing `authentication_action` map from Module D to Module C to Module B to `alb-ingress` - breaks (in a way that is very difficult to understand and debug; the end result is that `alb-ingress` receives an empty or incomplete map)
=> Fix authentication action. Don't use `map` variable for authentication action

aws/ecs/atlantis-repo-config.yaml, aws/ecs/atlantis.auto.tfvars.example, aws/ecs/atlantis.tf
* Update `atlantis` version
* Add `atlantis_repo_config` variable
* Remove `--allow-repo-config` variable
* https://github.com/cloudposse/terraform-aws-ecs-atlantis/pull/7
* Flag `--allow-repo-config` has been deprecated in favor of creating a server-side repo config file that applies the same configuration
* Use a server-side config file and point `--repo-config` to it
* https://github.com/runatlantis/atlantis/releases/tag/v0.7.0
* https://www.runatlantis.io/docs/configuring-atlantis.html
* https://www.runatlantis.io/docs/server-configuration.html
* https://www.runatlantis.io/docs/server-side-repo-config.html
* https://www.runatlantis.io/docs/repo-level-atlantis-yaml.html
=> [ecs/atlantis] Update `atlantis` version. Add `atlantis_repo_config` variable

aws/ecs/atlantis.tf
* [ecs/atlantis] Bump `terraform-aws-ecs-atlantis` version
* Fix GitHub webhooks
* https://github.com/cloudposse/terraform-aws-ecs-atlantis/pull/8
* https://github.com/cloudposse/terraform-aws-ecs-web-app/pull/31
* https://github.com/cloudposse/terraform-aws-ecs-codepipeline/pull/23
* https://github.com/cloudposse/terraform-github-repository-webhooks/pull/8
=> [ecs/atlantis] Bump `terraform-aws-ecs-atlantis` version

aws/ecs/default-backend.tf
* [ecs/atlantis] Bump `default_backend_web_app` version
* Use the same version of `web-app` for default backend and atlantis app
=> [ecs/atlantis] Bump `default_backend_web_app` version

aws/elasticsearch/main.tf, aws/elasticsearch/variables.tf
Include optional log cleanup module for when Elasticsearch is used to store Fluentd or Logstash logs, for example.
Keep disk usage under control
=> [elasticsearch] Include optional log cleanup module

aws/ecs/atlantis.tf, aws/ecs/default-backend.tf
* Update  `ecs/atlantis` version
* https://github.com/cloudposse/terraform-aws-ecs-atlantis/pull/12
* https://github.com/cloudposse/terraform-aws-ecs-web-app/pull/34
* https://github.com/cloudposse/terraform-aws-ecs-codepipeline/pull/25
=> Update  `ecs/atlantis` version

aws/ecs/vpc.tf
* [ecs/atlantis] Update `terraform-aws-dynamic-subnets` version
* Add the ability to choose NAT Gateways or NAT Instances to be deployed into public subnets to allow the servers in the private subnets to access the Internet
* https://github.com/cloudposse/terraform-aws-dynamic-subnets/pull/51
=> [ecs/atlantis] Update `terraform-aws-dynamic-subnets` version. Add the ability to choose NAT Gateways or NAT Instances

aws/vpc/main.tf, aws/vpc/variables.tf
Allow for deploying the VPC into fewer than all the availability zones
We typically only want to deploy into 3 availability zones, but prior to this PR the VPC deployed into every available availability zone, and, for example, `us-east-1` has 6 availability zones
=> [vpc] Allow for deploying the VPC into fewer than all the availability zones

aws/kops-aws-platform/efs-provisioner.tf, aws/kops/main.tf
Fetch `kops` availability zones and DNS zone ID from SSM parameter store rather than directly from Terraform `tfstate` file.
Support mult-region configuration where Terraform `tfstate` file is not in a single pre-determined location and there are multiple DNS zone IDs.
=> [kops][kops-aws-platform] Fetch kops information for EFS from SSM rather than tfstate

aws/ecr/kops_ecr_app.tf, aws/ecr/main.tf, aws/kops/main.tf, aws/kops/variables.tf
- [kops] Support multi-region clusters by allowing `kops` to use an existing S3 bucket in a different region for its state storage. Data is stored under cluster name, so it is no operational problem for multiple clusters to use the same S3 bucket. 
- [ecr] Fix an issue with Terraform "count"
- [kops] Some people want to run clusters in more than one AWS region within the same AWS account.
- [ecr] ECR module failed when setting both read-only and full-access principals. This updates the backend module to one that has that issue fixed.
=> [kops] Support multi-region kops clusters.[ecr] Fix TF "count" problem in ecr.

aws/teleport/main.tf
Enable stream view for cluster state table
Required by Teleport 4.x, possibly even as early as 3.2
=> Teleport 4 requires stream view for cluster state table

aws/kops-aws-platform/external-dns.tf
[kops-aws-platform] Expand external-dns IAM role to cover [`cert-manager`](https://github.com/jetstack/cert-manager) as well
Support `cert-manager` as replacement for obsolete `kube-lego`
=> [kops-aws-platform] Support cert-manager

aws/ecs/acm.tf, aws/vpc-peering-intra-account/Makefile, aws/vpc-peering-intra-account/main.tf, aws/vpc-peering-intra-account/outputs.tf, aws/vpc-peering-intra-account/variables.tf
Create `vpc-peering-intra-account`
Much easier-to-use than other VPC peering modules, because it requires both VPCs to be in the same account.
=> EasyVPC peering inside a single AWS account.

aws/elasticsearch/main.tf
[elasticsearch] Use relative pathname for lambda file
Keep filename consistent between Geodesic and Atlantis
=> [elasticsearch] Use relative pathname for lambda file

aws/acm/main.tf, aws/acm/variables.tf, aws/acm/versions.tf, aws/kops-aws-platform/autoscaler-role.tf, aws/kops-aws-platform/efs-provisioner.tf, aws/kops-aws-platform/flow-logs.tf, aws/kops-aws-platform/main.tf, aws/kops/main.tf
1. [kops-aws-platform] Create autoscaler role
1. [kops-aws-platform] Do not try to take over default security group of shared VPC
1. [acm] Optionally save certificate ARN in SSM
1. [acm] Upgrade to TF 0.12
1. Enable autoscaler to get authorization via `kiam`
1. VPC owner should manage default security group
1. Prevent copy-paste between certificate creation and usage
1. Migration to TF 0.12 as time allows
=>  [kops-aws-platform] Create autoscaler role

aws/kops-aws-platform/autoscaler-role.tf, aws/teleport/main.tf
1. [teleport] Add additional required permissions
2. [autoscaler-role] Change SSM parameter name
1. New permissions required in Teleport 4.0.5. See https://github.com/gravitational/teleport/issues/2963
2. Distinguish deployed auto-scaler from `kops` add-on
=> [teleport] Add additional required permissions

aws/kops-aws-platform/autoscaler-role.tf, aws/kops-aws-platform/efs-provisioner.tf, aws/kops-aws-platform/main.tf, aws/kops-aws-platform/variables.tf
[kops-aws-platofrm] Store EFS info in SSM for use by efs-provisioner
Avoid the need to copy and paste output of Terraform into input of Helmfile
=> [kops-aws-platofrm] Store EFS info in SSM for use by efs-provisioner

aws/grafana-backing-services/main.tf, aws/teleport/main.tf, aws/teleport/outputs.tf, aws/teleport/variables.tf
- [teleport] Configure version and proxy domain
- [grafana-backing-services] Remove unused `region` variable
- Previously configured by directly adding to SSM, this now supports changing the Teleport version using GitOps
- Unused variables are misleading at best
=> [teleport] Configure version and proxy domain

aws/elasticsearch/main.tf, aws/elasticsearch/variables.tf
[elasticsearch] log cleanup lambda suddenly stopped working with error 
```
ValueError: You can only send PreparedRequests
```
apparently due to a change in AWS. This update installs an updated lambda function that work in the current AWS environment
Restore functionality broken by external factors
=> [elasticsearch] Fix log cleanup module

aws/ecs/Makefile, aws/ecs/acm.tf, aws/ecs/alb.tf, aws/ecs/atlantis-repo-config.yaml, aws/ecs/atlantis.auto.tfvars.example, aws/ecs/atlantis.tf, aws/ecs/default-backend.tf, aws/ecs/dns.tf, aws/ecs/ecs.tf, aws/ecs/flow-logs.tf, aws/ecs/main.tf, aws/ecs/sns.tf, aws/ecs/variables.tf, aws/ecs/versions.tf, aws/ecs/vpc.tf
* [atlantis] Convert `ecs` project to terraform 0.12
* Keep up to date
* Update to latest TF version
* Use TF modules converted to 0.12
=> [atlantis] Convert `ecs` project to terraform 0.12

aws/vpc/main.tf
in new version:
* gateway and instance now use same EIP module
* to avoid reassigning IPs in case of switch between `gateway` and `instance` types
=> terraform-aws-dynamic-subnets upgrade

aws/elasticsearch/main.tf
* Pin right version for elastic search
* The release `0.3.1` point to terraform 12 code, but we need terraform 11 so use `0.3.2`
=> ElasticSearch pin right version

aws/elasticsearch/main.tf, aws/elasticsearch/variables.tf
* create_iam_service_linked_role variables added to pass to elasticsearch module
* to be able to disable creating `AWSServiceRoleForAmazonElasticsearchService`. For example in case it is already there
=> create_iam_service_linked_role variable added

aws/elasticsearch/main.tf, aws/elasticsearch/variables.tf
* `elasticsearch_subdomain_name` variable added
* to be able to override default value (var.name) with custom subdomain hostname
=> elasticsearch_subdomain_name variable added

aws/elasticsearch/main.tf
* terraform-aws-elasticsearch version bump
* to support `elasticsearch_subdomain_name` variable
=> terraform-aws-elasticsearch version bump

aws/elasticsearch/main.tf
* terraform-aws-elasticsearch version bump
* 0.3.4 was a broken release
=> terraform-aws-elasticsearch bumped again

aws/elasticsearch/main.tf
* [elasticsearch] list of `subnet_ids` is not sliced any more
* to avoid `ValidationException: You must specify exactly three subnets because you’ve set zone count to three` error.
=> elasticsearch subnets list lenght fix

aws/elasticsearch/main.tf, aws/elasticsearch/variables.tf
* Add `iam_role_arns` variable to specify additional IAM roles to allow access to the Elasticsearch domain
* When Elasticsearch is accessed from applications running on a Kubernetes cluster, the applications are usually running by assuming an IAM role using `kiam` or EKS Service Account IAM Roles. We need to be able to give the application's role permissions to access the ES domain without forcing the application code to assume another IAM role
=> Add `iam_role_arns` variable to specify additional IAM roles to allow access to the Elasticsearch domain

aws/elasticsearch/main.tf
A new version of `https://github.com/cloudposse/terraform-aws-elasticsearch` has been released and needs to be reflected here.
=> Bump terraform-aws-elasticsearch to 0.13.0

aws/elasticsearch/main.tf
* [elasticsearch] Bump `terraform-aws-elasticsearch` version
* When an output from a data source is used in `counts`, in some cases Terraform can't compute the counts throwing the errors (it's working in the Terratest, but does not work for some customers):
```
Error: Invalid count argument
on .terraform/modules/search_service_elasticsearch_master.elasticsearch/main.tf line 76, in resource "aws_iam_service_linked_role" "default":
76:   count            = var.enabled && var.create_iam_service_linked_role && length(data.aws_iam_role.default.*.id) == 0 ? 1 : 0
The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources …
```
=> [elasticsearch] Bump `terraform-aws-elasticsearch` version

README.md, aws/elasticsearch/main.tf, aws/elasticsearch/variables.tf
* Update `terraform-aws-lambda-elasticsearch-cleanup` version
* Added `enabled` and `artifact_url ` variables to the module
* When the `terraform-external-module-artifact` module is used in this module with `enabled` variable set to `false`, `terraform-external-module-artifact` needs to be disabled as well (otherwise it throws errors that it can't download the artifact)
* Allow to override the `artifact_url ` URL template
* https://github.com/cloudposse/terraform-aws-lambda-elasticsearch-cleanup/releases/tag/0.6.0
* https://github.com/cloudposse/terraform-external-module-artifact/releases/tag/0.3.0
=> Update `terraform-aws-lambda-elasticsearch-cleanup` version

aws/elasticsearch/main.tf, aws/elasticsearch/variables.tf
The default value is 2 in https://github.com/cloudposse/terraform-aws-elasticsearch/blob/master/variables.tf which is not suitable for accounts that have 3 AZ's. It needs to exposed so it can be overridden.
=> Add availability_zone_count variable

aws/sentry/rds.tf
* unnecessary Security Group removed
* to avoid duplicate Security Group rule error
=> avoid duplicate Security Group rule error

aws/sentry/aurora-postgres.tf, aws/sentry/elasticache-redis.tf, aws/sentry/main.tf, aws/sentry/rds.tf, aws/sentry/ses.tf, aws/sentry/variables.tf
* Add SES module that creates `domain identity`, IAM user that can send emails and verification DNS records in Route53
* To send emails via SES with sentry
=> [sentry] Added optional SES module for sending emails

aws/elasticsearch/main.tf, aws/elasticsearch/variables.tf
It's not possible to override the log publishing options provided by the module https://github.com/cloudposse/terraform-aws-elasticsearch.
=> Add missing log publishing options for Elasticsearch

modules/account/main.tf, modules/account/variables.tf
* [account] Change `organization_config` variable type
* Depending on the structure of the Organization/OUs/accounts configuration YAML, we can get this error if the objects inside the map are not the same type (don't have the same fields)
```
The given value is not valid for variable "organization_config": 
all map elements must have the same type.
```
=> [account] Change `organization_config` variable type

README.md, modules/eks-iam/alb-controller-iam-policy.json, modules/eks-iam/alb-controller.tf, modules/eks-iam/main.tf
- Add support for [aws-load-balancer-controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller) service account named `alb-controller`
- IAM component of  `aws-load-balancer-controller` support
=> Add support for alb-controller

.pre-commit-config.yaml, README.md, README.yaml, docs/terraform.md, modules/account-map/README.md, modules/account-settings/README.md, modules/account/README.md, modules/cloudtrail-bucket/README.md, modules/cloudtrail/README.md, modules/datadog-integration/README.md, modules/datadog-monitor/README.md, modules/dns-delegated/README.md, modules/dns-primary/README.md, modules/ecr/README.md, modules/efs/README.md, modules/eks-iam/README.md, modules/eks/README.md, modules/iam-delegated-roles/README.md, modules/iam-primary-roles/README.md, modules/opsgenie/README.md, modules/sso/README.md, modules/tfstate-backend/README.md, modules/transit-gateway/README.md, modules/vpc/README.md
* Updates pre-commit-terraform version to utilize latest terraform-docs version
* Updates all READMEs with latest updates from tf-docs
* Bunch of terraform-docs updates recently, so utilizing the latest ensures we're keeping up-to-date with the improved README format.
* Should be merged prior to #300 since this is breaking that PR's CI
=> chore: updates pre-commit-tf version + updates READMEs for newer tf-docs

Makefile
* adds a `upstream-component` Makefile task
* Simple helper to support upstreaming from a project directory... it's stupid, but figured we're going to be doing this from many project repositories as Cloud Posse invests more and more into the components system.
=> feat: adds upstream-component make target to make upstreaming easier

.github/workflows/pre-commit.yml, modules/account-map/README.md, modules/account-settings/README.md, modules/account/README.md, modules/cloudtrail-bucket/README.md, modules/cloudtrail/README.md, modules/datadog-integration/README.md, modules/datadog-monitor/README.md, modules/dns-delegated/README.md, modules/dns-primary/README.md, modules/ecr/README.md, modules/efs/README.md, modules/eks-iam/README.md, modules/eks/README.md, modules/elasticache-redis/README.md, modules/iam-delegated-roles/README.md, modules/iam-primary-roles/README.md, modules/opsgenie/README.md, modules/spacelift-worker-pool/README.md, modules/sso/README.md, modules/tfstate-backend/README.md, modules/transit-gateway/README.md, modules/vpc/README.md
* Used latest pre-commit.yml to fix terraform-docs install
* Ran `pre-commit run --all-files` locally using the same version of `terraform-docs` to pass the tests.
* The pre-commit install step seems broken in recent PRs and this should fix it by using the latest pre-commit workflow
* Blocks PR https://github.com/cloudposse/terraform-aws-components/pull/326
=> Use latest pre-commit.yml to fix terraform-docs install

modules/account-map/README.md, modules/github-runners/variables.tf, modules/zscaler/README.md, modules/zscaler/context.tf, modules/zscaler/default.auto.tfvars, modules/zscaler/main.tf, modules/zscaler/outputs.tf, modules/zscaler/providers.tf, modules/zscaler/templates/userdata.sh.tmpl, modules/zscaler/variables.tf, modules/zscaler/versions.tf
* Upstream `zscaler` component
* Others can now provision ZScaler Private Access Connector instances on Amazon Linux 2
N/A
To pass pre-commit hook
```shell
tfenv install 0.13.5
make readme
pre-commit run --show-diff-on-failure --color=always --all-files
git add modules/
```
=> Upstream `zscaler` component

README.md, docs/targets.md, modules/elasticsearch/README.md, modules/elasticsearch/context.tf, modules/elasticsearch/default.auto.tfvars, modules/elasticsearch/main.tf, modules/elasticsearch/outputs.tf, modules/elasticsearch/providers.tf, modules/elasticsearch/remote-state.tf, modules/elasticsearch/variables.tf, modules/elasticsearch/versions.tf
* Upstream `elasticsearch` component
* Bumped version from 0.30.0 to 0.33.0 (latest non pre-release)
* Install kibana with a security group, iam role, and configured elasticsearch
* https://github.com/cloudposse/terraform-aws-elasticsearch
To pass pre-commit hook
```shell
tfenv install 0.13.5
tfenv use 0.13.5
make readme
pre-commit run --show-diff-on-failure --color=always --all-files
git add modules/elasticsearch
```
=> feat: Upstream `elasticsearch` component

modules/cloudwatch-logs/README.md, modules/cloudwatch-logs/context.tf, modules/cloudwatch-logs/default.auto.tfvars, modules/cloudwatch-logs/main.tf, modules/cloudwatch-logs/outputs.tf, modules/cloudwatch-logs/providers.tf, modules/cloudwatch-logs/variables.tf, modules/cloudwatch-logs/versions.tf
* Upstream `cloudwatch-logs`
* Sets up the cloudwatch logs
* https://github.com/cloudposse/terraform-aws-cloudwatch-logs/releases/tag/0.4.2
To pass pre-commit hook
```shell
tfenv install 0.13.5
tfenv use 0.13.5
make readme
pre-commit run --show-diff-on-failure --color=always --all-files
git add modules/cloudwatch-logs
```
=> feat: Upstream `cloudwatch-logs`

modules/cloudwatch-logs/README.md, modules/cloudwatch-logs/main.tf, modules/cloudwatch-logs/providers.tf
* Upgrade `cloudwatch-logs` to `0.4.3`
* This no longer has the dependency https://github.com/cloudposse/terraform-aws-iam-policy-document-aggregator/tree/master
* This issue was causing spacelift to show differences for each cloudwatch-logs stack
* Previous PR https://github.com/cloudposse/terraform-aws-components/pull/344
* Upstream module PR https://github.com/cloudposse/terraform-aws-cloudwatch-logs/pull/16
=> feat: Upgrade `cloudwatch-logs` to `0.4.3`

modules/datadog-integration/main.tf, modules/datadog-monitor/main.tf
- Update the versions of the datadog components used in the all-new-components branch
- in order to use the additional integration possibilities
=> Update datadog component versions

modules/eks/default.auto.tfvars, modules/eks/eks-node-groups.tf, modules/eks/modules/node_group_by_az/main.tf, modules/eks/modules/node_group_by_az/variables.tf, modules/eks/modules/node_group_by_region/variables.tf, modules/eks/variables.tf
- Pass the `caacity_type` variable to the underlying `terraform-aws-eks-node-group` module
- To enable the creation of spot-instance based node groups
=> Pass `capacity_type` to the `terraform-aws-eks-node-group` module

modules/dns-delegated/acm.tf
* Marks the `acm_ssm_parameter` output in `dns-delegated/acm.tf` as `sensitive = true`
* Fixes issue with 0.15+ not liking that output being in the clear:
=> fix: marks dns-delegated acm_ssm_parameter output as sensitive

modules/github-runners/README.md, modules/github-runners/main.tf, modules/github-runners/templates/deregister-github-runner, modules/github-runners/templates/user-data.sh, modules/github-runners/variables.tf
Github now supports obtaining a scoped (Organization or Repository) registration token directly through the UI, which would eliminate the need for any kind of long-lived credentials to be stored. It would be great if we could specify the registration token rather than a PAT and the actions-runner-controller could just use the registration token directly rather than using the API to obtain one.
Currently, the component supports providing a Github Personal Access Token (PAT) and uses that token to call the Github API to request a Runner registration token. Using this method requires users to create and store a privileged (Admin scoped) token that has more permissions than it requires.
* Additional information in the [RefArch documentation](https://cloudposse.atlassian.net/wiki/spaces/REFARCH …
=> update github-runners to support using registration token directly

modules/snowflake-account/README.md, modules/snowflake-account/context.tf, modules/snowflake-account/default.auto.tfvars, modules/snowflake-account/introspection.mixin.tf, modules/snowflake-account/main.tf, modules/snowflake-account/outputs.tf, modules/snowflake-account/providers.tf, modules/snowflake-account/remote-state.tf, modules/snowflake-account/variables.tf, modules/snowflake-account/versions.tf, modules/snowflake-database/README.md, modules/snowflake-database/context.tf, modules/snowflake-database/default.auto.tfvars, modules/snowflake-database/grants.tf, modules/snowflake-database/introspection.mixin.tf, modules/snowflake-database/main.tf, modules/snowflake-database/providers.tf, modules/snowflake-database/remote-state.tf, modules/snowflake-database/variables.tf, modules/snowflake-database/versions.tf
- Added modules for `snowflake-account` and `snowflake-database`
- Provided examples for using Snowflake
- `snowflake-account` creates the requirements for running snowflake components
- `snowflake-database` is an example snowflake component
* If you are adding a new component to `terraform-aws-components`, you must add a label to the pull request specifying the earliest major and minor versions of Terraform for which the component must remain backwards compatible. (E.g., `terraform/0.15`, `terraform/0.12`, etc.). If compatibility with pre-1.0 versions of Terraform is not required, just select the `terraform/1.x` label.
* The chosen label will determine the version of Terraform that will be used in this pull request's `pre-commit` status checks.
=> `snowflake-account` and `snowflake-database`

modules/argocd-repo/README.md, modules/argocd-repo/applicationset.tf, modules/argocd-repo/context.tf, modules/argocd-repo/default.auto.tfvars, modules/argocd-repo/git-files.tf, modules/argocd-repo/main.tf, modules/argocd-repo/outputs.tf, modules/argocd-repo/providers.tf, modules/argocd-repo/ssm.tf, modules/argocd-repo/templates/.gitignore.tpl, modules/argocd-repo/templates/CODEOWNERS.tpl, modules/argocd-repo/templates/PULL_REQUEST_TEMPLATE.md, modules/argocd-repo/templates/README.md.tpl, modules/argocd-repo/templates/applicationset.yaml.tpl, modules/argocd-repo/variables.tf, modules/argocd-repo/versions.tf
- Added component for `argocd-repo`
- Setting up vendoring in CPLIVE requires up-to-date, upstreamed components
- CPLIVE-279
=> CPLIVE-279: Added `argocd-repo`

modules/account/main.tf
* Ignore changes to the iam_user_access_to_billing attribute on `aws_organizations_account.organization_accounts` and `aws_organizations_account.organizational_units_accounts`
* This is mainly to support importing of accounts, but also would stop the account being replaced if the value is changed, which is probably what is wanted in most cases.
* The AWS [API](https://docs.aws.amazon.com/organizations/latest/APIReference/API_DescribeAccount.html) doesn't allow this value to be read
* When an account is imported, `iam_user_access_to_billing` isn't imported due to the value not existing in the API response. Upon running the account component again, TF wants to destroy the resource to apply this value.
* Other than editing the TF state, this lifecycle block will resolve the issue.
* None
=> add ignore_changes block for iam_user_access_to_billing to account resources

modules/s3-bucket/README.md, modules/s3-bucket/main.tf, modules/s3-bucket/variables.tf
- Added `var.iam_policy_statements` and use it to set the `iam_policy_statements` for `"cloudposse/iam-policy/aws"`
- Previously had `source_policy_documents` set that value. That variable is a list of policies, not an actual policy statement list. Updated to correct variable
- Required to resolve issue with AWS Global Accelerator. See [Slack thread](https://cloudposse.slack.com/archives/CA4TC65HS/p1660238441939829)
=> Correct `iam_policy_statements` for `s3-bucket` Component

modules/lakeformation/README.md, modules/lakeformation/main.tf, modules/lakeformation/variables.tf
* Allowing user to specify if the service-linked role should be created or not, and adding some logic to determine which role to use
* Updating example in `README`
=> Updating role_arn logic and README example

modules/aurora-mysql-resources/README.md, modules/aurora-mysql-resources/context.tf, modules/aurora-mysql-resources/main.tf, modules/aurora-mysql-resources/modules/mysql-user/context.tf, modules/aurora-mysql-resources/modules/mysql-user/default.auto.tfvars, modules/aurora-mysql-resources/modules/mysql-user/main.tf, modules/aurora-mysql-resources/modules/mysql-user/outputs.tf, modules/aurora-mysql-resources/modules/mysql-user/variables.tf, modules/aurora-mysql-resources/modules/mysql-user/versions.tf, modules/aurora-mysql-resources/outputs.tf, modules/aurora-mysql-resources/providers.tf, modules/aurora-mysql-resources/remote-state.tf, modules/aurora-mysql-resources/variables.tf, modules/aurora-mysql-resources/versions.tf, modules/aurora-mysql/README.md, modules/aurora-mysql/cluster-regional.tf, modules/aurora-mysql/context.tf, modules/aurora-mysql/default.auto.tfvars, modules/aurora-mysql/kms.tf, modules/aurora-mysql/main.tf, modules/aurora-mysql/outputs.tf, modules/aurora-mysql/providers.tf, modules/aurora-mysql/remote-state.tf, modules/aurora-mysql/ssm.tf, modules/aurora-mysql/variables.tf, modules/aurora-mysql/versions.tf
- Added both `aurora-mysql` and `aurora-mysql-resources`
- These components are not yet upstream
- Created these components from the outdated single component, `aurora-mysql`
- [Slack context](https://cloudposse.slack.com/archives/CA4TC65HS/p1660338132983349)
=> Add `aurora-mysql` Components

modules/github-runners/templates/user-data.sh
* Use a softlink instead of cp in gh runner asg
* Avoid a shared library issue in awscli v2
* Client issue
N/A
=> github-runners: Use a softlink instead of cp in gh runner asg

modules/redis/README.md
- Added required config to redis readme
- without this setting, terraform will always show changes on plans
- N/A
=> Upstream `eks/redis`

modules/elasticache-redis/main.tf, modules/elasticache-redis/outputs.tf
* elasticache-redis: Use `cluster_name` override and correct dns env
* Updates
N/A
=> elasticache-redis: Use `cluster_name` override and correct dns env

.github/workflows/pre-commit-check-and-autocommit-changes.yaml
- Use a default Terraform version for formatting when no labels are present
- Requiring a label per PR to determine the Terraform version is extra work that also leads to likely "flapping" if one PR uses a different label than another. Labels should only be required when there is some reason not to use the default.
=> Set default terraform version rather than requiring (inconsistent) tags

modules/github-runners/templates/user-data.sh
* Use `ln -sf`
* Use `cp` instead of `mv`
* Use `-o` flag for `unzip` to overwrite files if they have already been unzipped
* Add a few echo statements so it's clear where the script fails
* Keep runners up to date
* Keep script idempotent
- N/A
=> Small userdata fixes for gh runners

modules/datadog-agent/main.tf, modules/datadog-agent/outputs.tf
* output cannot be `""` as it mismatches other type if enabled
* tags must be a set, but function call requires a list
* Bugfixes
* #482
=> bugfixes from `datadog-agent` upstream

modules/datadog-monitor/README.md, modules/datadog-monitor/catalog/monitors/aurora.yaml, modules/datadog-monitor/catalog/monitors/ec2.yaml, modules/datadog-monitor/catalog/monitors/efs.yaml, modules/datadog-monitor/catalog/monitors/elb.yaml, modules/datadog-monitor/catalog/monitors/host.yaml, modules/datadog-monitor/catalog/monitors/k8s.yaml, modules/datadog-monitor/catalog/monitors/rabbitmq.yaml, modules/datadog-monitor/catalog/monitors/rds.yaml, modules/datadog-monitor/main.tf
* Datadog Platform Monitors expect a map for tags, it then converts it to an array in DD Format. This PR updates the default catalog to use maps not arrays
* Updating platform version
* Upstream
=> `datadog-monitor` version updates and monitors use maps for tags

.pre-commit-config.yaml, modules/s3-bucket/remote-state.tf
* Currently the s3-bucket module requires a value for `tenant`, either set via context or `account_map_tenant_name`. This change relaxes this requirement.
* Some consumers of this module don't use tenant in resource naming
* None
=> s3-bucket: allow usage without providing a value for `tenant`

modules/datadog-monitor/main.tf
* Allows `enabled: false` on monitors to succeed in merge
* bugfix introduced from upstream a while ago
error:
```
│ Error: Inconsistent conditional result types
│ 
│   on main.tf line 92, in module "datadog_monitors_merge":
│   92:     (local.local_datadog_monitors_enabled) ? module.local_datadog_monitors_yaml_config.map_configs : {},
│     ├────────────────
│     │ local.local_datadog_monitors_enabled is true
│     │ module.local_datadog_monitors_yaml_config.map_configs is object with 38 attributes
│ 
│ The true and false result expressions must have consistent types. The 'true' value includes object attribute "aurora-replica-lag", which is absent in the 'false' value.
╵
```
=> `datadog-monitors` allow specific monitors to be disabled during merge

modules/ssm-parameters/README.md, modules/ssm-parameters/context.tf, modules/ssm-parameters/default.auto.tfvars, modules/ssm-parameters/main.tf, modules/ssm-parameters/outputs.tf, modules/ssm-parameters/providers.tf, modules/ssm-parameters/variables.tf, modules/ssm-parameters/versions.tf
* Adds a new component: `ssm-parameters`
* We use this component on Masterpoint projects to manage SSM Parameter Store resources in a GitOps-ish fashion.
* It enables managing secrets via sops and seeding them into SSM Params -- This be useful to reduce manual operations around secrets.
* It also supports managing normal SSM Params that are not secrets in the case that is useful for non-secret config. 
* None
=> feat: adds initial cut of the ssm-parameters component

modules/account-quotas/README.md, modules/account-quotas/context.tf, modules/account-quotas/main.tf, modules/account-quotas/outputs.tf, modules/account-quotas/providers.tf, modules/account-quotas/variables.tf, modules/account-quotas/versions.tf
- Add `account-quotas` component to manage account service quota increase requests
- Add service quotas to the infrastructure that can be represented in code
Cloud Posse has a [service quotas module](https://github.com/cloudposse/terraform-aws-service-quotas), but it has issues, such as not allowing the service to be specified by name, and not having well documented inputs. It also takes a list input, but Atmos does not merge lists, so a map input is more appropriate. Overall I like this component better, and if others do, too, I will replace the existing module (only at version 0.1.0) with this code.
=> Add account-quotas component

modules/eks/actions-runner-controller/README.md, modules/eks/actions-runner-controller/main.tf, modules/eks/actions-runner-controller/provider-helm.tf, modules/eks/actions-runner-controller/remote-state.tf, modules/eks/actions-runner-controller/variables.tf, modules/eks/actions-runner-controller/versions.tf
- Support and prefer authentication via GitHub app
- Support and prefer webhook-based autoscaling
- GitHub app is much more restricted, plus has higher API rate limits
- Webhook-based autoscaling is proactive without being overly expensive
=> [eks/actions-runner-controller] Auth via GitHub App, prefer webhook auto-scaling

modules/iam-role/README.md, modules/iam-role/context.tf, modules/iam-role/main.tf, modules/iam-role/outputs.tf, modules/iam-role/providers.tf, modules/iam-role/variables.tf, modules/iam-role/versions.tf
- Upstream iam-role component
- Create simple IAM roles
- https://github.com/cloudposse/terraform-aws-iam-role
=> Upstream iam-role component

modules/vpc/README.md, modules/vpc/main.tf, modules/vpc/remote-state.tf, modules/vpc/variables.tf
* Set VPC to use region-less AZs
* Prevent having to set VPC AZs within global region defaults
* CPLIVE-320
=> CPLIVE-320: Set VPC to use region-less AZs

modules/aws-sso/README.md, modules/aws-sso/main.tf, modules/aws-sso/policy-TerraformUpdateAccess.tf, modules/aws-sso/remote-state.tf, modules/aws-sso/variables.tf, modules/aws-sso/versions.tf
* Changes for supporting [Refarch Scaffold](github.com/cloudposse/refarch-scaffold)
* TerraformUpdateAccess permission set added
* Allow SSO users to update dynamodb/s3 for terraform backend
=> fix(aws-sso): add missing tf update perms

modules/account-map/modules/iam-roles/variables.tf, modules/aws-sso/main.tf
* remove hardcoding for root account moniker
* change default tenant from `gov` to `core` (now convention)
* tenant is not included in the account prefix. In this case, changed to be 'core'
* most accounts do not use `gov` as the root tenant
=> fix(aws-sso): dont hardcode account name for root

modules/eks/karpenter/main.tf
Based on https://github.com/aws/karpenter/blob/92b3d4a0b029cae6a9d6536517ba42d70c3ebf8c/charts/karpenter/values.yaml#L129-L142 all these should go under settings.aws
Ensure compatibility with the new charts
Based on https://github.com/aws/karpenter/blob/92b3d4a0b029cae6a9d6536517ba42d70c3ebf8c/charts/karpenter/values.yaml
=> Sync karpenter chart values with the schema

modules/dns-primary/README.md, modules/dns-primary/acm.tf
* in dns-primary, revert version of acm module 0.17.0 -> 0.16.2 (17 is a preview)
* primary zones must be specified now that names are trimmed before the dot (.)
=> fix(dns-primary/acm): include zone_name arg

modules/eks/metrics-server/default.auto.tfvars
Upgrade metrics-server
Tested on k8s 1.24 via `kubectl get --raw "/apis/metrics.k8s.io/v1beta1/nodes"`
* The previous one was so old that bitnami has even removed the chart.
=> Update k8s metrics-server to latest

modules/ec2-client-vpn/README.md, modules/ec2-client-vpn/main.tf
* Bump Versin of EC2 Client VPN
* Bugfixes issue with TLS provider
* https://github.com/cloudposse/terraform-aws-ec2-client-vpn/pull/58
* https://github.com/cloudposse/terraform-aws-ssm-tls-self-signed-cert/pull/20
=> EC2 Client VPN Version Bump

modules/vpc/README.md
* Stack example has an old variable defined
* `The root module does not declare a variable named "eks_tags_enabled" but a value was found in file "uw2-automation-vpc.terraform.tfvars.json".`
=> Remove extra var from stack example

modules/account-map/modules/roles-to-principals/main.tf, modules/aws-sso/README.md, modules/aws-sso/main.tf, modules/aws-sso/outputs.tf, modules/aws-sso/policy-AdminstratorAccess.tf, modules/aws-sso/policy-BillingAdministratorAccess.tf, modules/aws-sso/policy-BillingReadOnlyAccess.tf, modules/aws-sso/policy-DNSAdministratorAccess.tf, modules/aws-sso/policy-Identity-role-RoleAccess.tf, modules/aws-sso/policy-Identity-role-TeamAccess.tf, modules/aws-sso/policy-PoweruserAccess.tf, modules/aws-sso/policy-ReadOnlyAccess.tf, modules/aws-sso/policy-TerraformUpdateAccess.tf, modules/aws-sso/remote-state.tf, modules/aws-sso/variables.tf
* Upgraded `aws-sso` to use `0.7.1` modules
* Updated `account-map/modules/roles-to-principals` to support assume role from SSO users in the identity account
* Adjusted `aws-sso/policy-Identity-role-RoleAccess.tf` to use the identity account name vs the stage so it supports names like `core-identity` instead of just `identity`
* `aws-sso` users could not assume role to plan/apply terraform locally
* using `core-identity` as a name broke the `aws-sso` policy since account `identity` does not exist in `full_account_map`
=> SSO upgrades and Support for Assume Role from Identity Users

modules/github-runners/README.md, modules/github-runners/main.tf, modules/github-runners/templates/user-data.sh, modules/github-runners/variables.tf
* Added optional support for separating runners by groups
NOTE: I don't know if the default of `default` is valid or if it is `Default`. I'll confirm this soon.
* Groups are supported by GitHub and allow for Actions to target specific runners by group vs by label
* https://docs.github.com/en/actions/hosting-your-own-runners/managing-access-to-self-hosted-runners-using-groups
=> github-runners add support for runner groups

modules/datadog-monitor/catalog/monitors/aurora.yaml, modules/datadog-monitor/catalog/monitors/ec2.yaml, modules/datadog-monitor/catalog/monitors/efs.yaml, modules/datadog-monitor/catalog/monitors/elb.yaml, modules/datadog-monitor/catalog/monitors/host.yaml, modules/datadog-monitor/catalog/monitors/k8s.yaml, modules/datadog-monitor/catalog/monitors/rabbitmq.yaml, modules/datadog-monitor/catalog/monitors/rds.yaml
* grouping by team helps ensure the team tag is sent to Opsgenie
* ensures most data is fed to a valid team tag instead of `@opsgenie-`
=> `datadog-monitors`: Team Grouping

modules/datadog-lambda-forwarder/README.md, modules/datadog-lambda-forwarder/main.tf, modules/datadog-lambda-forwarder/variables.tf
This module attempts to do length() on the value for s3_buckets.
We are not using s3_buckets, and it defaults to null, so length() fails.
=> datadog-lambda-forwarder: if s3_buckets not set, module fails

modules/datadog-monitor/catalog/monitors/rds.yaml
* Update monitor to have default CP tags
=> bugfix: rds anomalies monitor not sending team information

modules/eks/actions-runner-controller/main.tf
* use coalesce instead of try, as we need a value passed in here
=> `eks/actions-runner-controller`: use coalesce

modules/eks/external-dns/README.md, modules/eks/external-dns/main.tf, modules/eks/external-dns/remote-state.tf, modules/eks/external-dns/variables.tf, modules/eks/platform/README.md, modules/eks/platform/main.tf, modules/eks/platform/providers.tf, modules/eks/platform/remote-state.tf, modules/eks/platform/variables.tf, modules/eks/platform/versions.tf
* `eks/external-dns` support `dns-primary`
* `eks/platform` support json query remote components outputs
* `vanity domain` pattern support by `eks/external-dns`
* Improve flexibility of `eks/platform`
=> Improve platform and external-dns for release engineering

modules/spacelift/README.md, modules/spacelift/main.tf, modules/spacelift/variables.tf
* update spacelift component to 0.55.0
* support feature flag for spacelift_stack_dependency resource
* [spacelift module 0.55.0](https://github.com/cloudposse/terraform-spacelift-cloud-infrastructure-automation/releases/tag/0.55.0)
=> chore(spacelift): update with dependency resource

.github/CODEOWNERS
* Update CODEOWNERS to remove contributors
* Require approval from engineering team (or in some cases admins) for all changes, to keep better quality control on this repo
=> Update CODEOWNERS to remove contributors

mixins/provider-datadog.tf, mixins/providers-aws-superadmin.tf, mixins/providers.tf
*  Copies some common providers to the mixins folder
* Have a central place where our common providers are held.
=> add providers to `mixins` folder

modules/eks/actions-runner-controller/README.md
* update example config to use 30m for webhook_startup_timeout
* add docs on configuration for webhook scaleUpTriggers
* runners will scale back down at the end of duration and could interrupt work
* while 30m is a recommended default, long durations may be necessary
* [scaling runners](https://github.com/actions/actions-runner-controller/blob/master/docs/automatically-scaling-runners.md)
=> docs: eks/actions-runner-controller webhook scaleUpTrigger config

modules/eks/idp-roles/README.md, modules/eks/idp-roles/versions.tf, modules/elasticsearch/README.md, modules/elasticsearch/versions.tf
added missing provider version pins
missing provider versions, required for bats
#626 
#628, #627
=> Missing Version Pins for Bats

rootfs/usr/local/bin/aws-config
Update `aws-config` command:
- Add `teams` command and suggest "aws-config-teams" file name instead of "aws-config-saml" because we want to use "aws-config-teams" for both SAML and SSO logins with Leapp handling the difference.
- Add `help` command
- Add more extensive help
- Do not rely on script generated by `account-map` for command `main()` function
- Reflect latest design pattern
- Improved user experience
=> [aws-config] Update usage info, add "help" and "teams" commands

modules/eks/efs-controller/resources/iam_policy_statements.yaml
* Update the iam policy for eks/efs-controller
* Older permissions will not work with new versions of the controller
* [official iam policy
sample](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/docs/iam-policy-example.json)
=> fix: eks/efs-controller iam policy updates

modules/ecs-service/main.tf
Add an option to attach the `iam-policy` resource to `ecs-service`
This policy is already created, but is missing its attachment. We should attach this to the resource when enabled
https://cloudposse.slack.com/archives/CA4TC65HS/p1683729972134479
=> Add `iam-policy` to `ecs-service`

modules/eks/cluster/main.tf
- Remove (broken) root access to EKS clusters
- Include session name in audit trail of users accessing EKS
- Test code granting access to all `root` users and roles was accidentally left in #645 and breaks when Tenants are part of account names
- There is no reason to allow `root` users to access EKS clusters, so even when this code worked it was wrong
- Audit trail can keep track of who is performing actions
- https://aws.github.io/aws-eks-best-practices/security/docs/iam/#use-iam-roles-when-multiple-users-need-identical-access-to-the-cluster
=> Remove (broken) root access to EKS clusters

modules/account/README.md, modules/account/main.tf
* Bump [cloudposse/config/yaml](https://github.com/cloudposse/terraform-yaml-config) module dependency from version 1.0.1 to 1.0.2
* 1.0.1 still uses hashicorp/template provider, which has no M1 binary equivalent, 1.0.2 already uses the cloudposse version which has the binary
* (https://github.com/cloudposse/terraform-yaml-config/releases/tag/1.0.2)
=> bump config yaml dependency on account component as it still depends on hashicorp template provider

modules/eks/alb-controller-ingress-group/default.auto.tfvars, modules/eks/alb-controller-ingress-group/main.tf
- corrected tag reference for pull lb data resource
- the tags that are used to pull the ALB that's created should be filtering using the same group_name that is given when the LB is created
- n/a
=> `eks/alb-controller-ingress-group`: Corrected Tags to pull LB Data Resource

modules/datadog-monitor/catalog/monitors/lambda-log-forwarder.yaml, modules/datadog-monitor/catalog/monitors/lambda.yaml
* add lambda error monitor
* add datadog lambda log forwarder config monitor
* Observability
=> feat: add lambda monitors to datadog-monitor

modules/s3-bucket/README.md, modules/s3-bucket/main.tf
* Upgraded S3 Bucket module version
* Upgrade S3 Bucket module to support recent changes made by AWS team regarding ACL
* https://github.com/cloudposse/terraform-aws-s3-bucket/pull/178
=> Upgrade S3 Bucket module to support recent changes made by AWS team regarding ACL

modules/eks/alb-controller/main.tf
* Update `eks/alb-controller` controller IAM policy
* Email from AWS: 
> On June 1, 2023, we will be adding an additional layer of security to ELB ‘Create*' API calls where API callers must have explicit access to add tags in their Identity and Access Management (IAM) policy. Currently, access to attach tags was implicitly granted with access to 'Create*' APIs.
* [Updated IAM policy](https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3068)
=> Update ALB controller IAM policy

modules/aws-team-roles/README.md, modules/aws-team-roles/additional-policy-map.tf, modules/aws-team-roles/main.tf, modules/aws-teams/README.md, modules/aws-teams/additional-policy-map.tf, modules/aws-teams/main.tf
- Add `additional-policy-map.tf` as glue meant to be replaced by customers with map of their custom policies.
- Currently, custom polices have to be manually added to the map in `main.tf`, but that gets overwritten with every vendor update. Putting that map in a separate, optional file allows for the custom code to survive vendoring.
=> Preserve custom roles when vendoring in updates

modules/cloudtrail-bucket/README.md, modules/cloudtrail-bucket/main.tf, modules/datadog-synthetics/README.md, modules/datadog-synthetics/remote-state.tf, modules/spacelift-worker-pool/README.md, modules/spacelift-worker-pool/main.tf
- Update modules for Terraform AWS provider v5
- Provider version 5.0.0 was released with breaking changes. This fixes the breakage.
- [v5 upgrade guide](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-5-upgrade)
- [v5.0.0 Release Notes](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.0.0)
=> Update modules for Terraform AWS provider v5

modules/eks/external-secrets-operator/README.md, modules/eks/external-secrets-operator/helm-variables.tf, modules/eks/external-secrets-operator/main.tf, modules/eks/external-secrets-operator/provider-helm.tf, modules/eks/external-secrets-operator/versions.tf
For `eks/external-secrets-operator`:
* Normalize variables, update dependencies
* Exclude Kubernetes provider v2.21.0
* Bring in line with other Helm-based modules
* Take advantage of improvements in dependencies
* [Breaking change in Kubernetes provider v2.21.0](https://github.com/hashicorp/terraform-provider-kubernetes/pull/2084)
=> [eks/external-secrets-operator] Normalize variables, update dependencies

modules/eks/external-secrets-operator/README.md, modules/eks/external-secrets-operator/examples/app-secrets.yaml, modules/eks/external-secrets-operator/examples/external-secrets.yaml
- Update documentation and examples for `eks/external-secrets-operator` to properly show that the component creates `ClusterSecretStores` and not `SecretStores` (namespaced)
- Previous documentation lead to improper (failed) operation
=> Fix documentation for eks/external-secrets-operator

modules/alb/main.tf
* Apply the HTTPS policy
* The policy was unused so it was defaulting to an old policy
=> alb: use the https_ssl_policy

modules/github-oidc-provider/README.md, modules/github-oidc-provider/scripts/get_github_oidc_thumbprint.sh, modules/github-oidc-provider/variables.tf
- include both thumbprints for GitHub OIDC
- There are two possible intermediary certificates for the Actions SSL certificate and either can be returned by Github's servers, requiring customers to trust both. This is a known behavior when the intermediary certificates are cross-signed by the CA. 
- https://github.blog/changelog/2023-06-27-github-actions-update-on-oidc-integration-with-aws/
=> Add Missing `github-oidc-provider` Thumbprint

modules/github-oidc-provider/README.md, modules/github-oidc-provider/providers.tf
- This updates `provider.tf` to provide compatibility with various legacy configurations as well as the current reference architecture
- This update does NOT require updating `account-map`
After installing this version of the component, you may need to change the configuration in your stacks.
- If you have dynamic Terraform roles enabled, then this should be configured like a normal component. The previous component may have required you to set 
```yaml
backend:
s3:
role_arn: null
````
and **that configuration should be removed** everywhere.
- If you only use SuperAdmin to deploy things to the `identity` account, then for the `identity` (and `root`, if applicable) account ***only***, set
```yaml
backend:
s3:
role_arn: null
vars:
superadmin: true
````
**Deployments to other accounts should …
=> [github-oidc-provider] extra-compatible provider

modules/bastion/README.md, modules/bastion/main.tf, modules/github-runners/README.md, modules/github-runners/main.tf
- bumped ASG module version, `cloudposse/ec2-autoscale-group/aws` to `0.35.0`
- Recent versions of this module resolve errors for these components
- https://github.com/cloudposse/terraform-aws-ec2-autoscale-group
=> Bump `cloudposse/ec2-autoscale-group/aws` to `0.35.0`

modules/account-map/README.md, modules/account-map/main.tf, modules/account-map/outputs.tf
- Restore backwards compatibility of `account-map` output
- PR #715 removed outputs from `account-map` that `iam-roles` relied on. Although it removed the references in `iam-roles`, this imposed an ordering on the upgrade: the `iam-roles` code had to be deployed before the module could be applied. That proved to be inconvenient. Furthermore, if a future `account-map` upgrade added outputs that iam-roles` required, neither order of operations would go smoothly. With this update, the standard practice of applying `account-map` before deploying code will work again.
=> Restore backwards compatibility of account-map output

modules/spacelift/spaces/README.md, modules/spacelift/spaces/main.tf
- bumped module version for `terraform-spacelift-cloud-infrastructure-automation`
- New policy added to `spaces`
- https://github.com/cloudposse/terraform-spacelift-cloud-infrastructure-automation/releases/tag/1.1.0
=> Bump `spaces` module versions

modules/gitops/github-actions-iam-policy.tf
- allow actions on table resources
- required to be able to query using a global secondary index
- https://github.com/cloudposse/github-action-terraform-plan-storage/pull/16
=> Upstream `gitops` Policy Update

modules/eks/alb-controller/main.tf
- Make the `alb-controller` default Ingress actually the default Ingress
- When setting `default_ingress_enabled = true` it is a reasonable expectation that the deployed Ingress be marked as the Default Ingress. The previous code suggests this was the intended behavior, but does not work with the current Helm chart and may have never worked.
=> Make alb-controller default Ingress actually the default Ingress

modules/aws-teams/policy-team-role-access.tf
- [aws-teams] Remove obsolete restriction on assuming roles in the `identity` account
Some time ago, there was an implied permission for any IAM role to assume any other IAM role in the same account if the originating role had sufficient permissions to perform `sts:AssumeRole`. For this reason, we had an explicit policy against assuming roles in the `identity` account.
AWS has removed that implied permission and now requires all roles to have explicit trust policies. Our current Team structure requires Teams (e.g. `spacelift`) to be able to assume roles in `identity` (e.g. `planner`). Therefore, the previous restriction is both not needed and actually hinders desired operation.
=> [aws-teams] Remove obsolete restriction on assuming roles in identity account

modules/alb/README.md, modules/alb/main.tf, modules/alb/remote-state.tf, modules/alb/variables.tf, modules/ssm-parameters/README.md, modules/ssm-parameters/main.tf, modules/ssm-parameters/variables.tf, modules/waf/README.md
- `alb` component can get the ACM cert from either `dns-delegated` or `acm`
- Support deploying `ssm-parameters` without SOPS
- `waf` requires a value for `visibility_config` in the stack catalog
- resolving bugs while deploying example components
- https://cloudposse.atlassian.net/browse/JUMPSTART-1185
=> `alb` and `ssm-parameters` Upstream for Basic Use

modules/elasticache-redis/modules/redis_cluster/main.tf
- Bump `elasticache-redis` module 
- Resolve issues with terraform provider v5
- https://github.com/cloudposse/terraform-aws-elasticache-redis/issues/199
=> Bump `elasticache-redis` Module

modules/elasticsearch/README.md, modules/elasticsearch/main.tf
- bump version of `lambda-elasticsearch-cleanup` module
- Support Terraform provider v5
- https://github.com/cloudposse/terraform-aws-lambda-elasticsearch-cleanup/pull/48
=> Bump `lambda-elasticsearch-cleanup` module

modules/spa-s3-cloudfront/README.md, modules/spa-s3-cloudfront/main.tf, modules/spa-s3-cloudfront/remote-state.tf
- Upstream changes to `spa-s3-cloudfront`
- Updated the included modules to support Terraform v5
- Handle disabled WAF from remote-state
- https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/pull/284
=> Upstream `spa-s3-cloudfront`

modules/s3-bucket/main.tf
* Pass s3_object_ownership variable into s3 module
* I think it was accidentally not included
* Make possible to disable ACL from stack config
* https://github.com/cloudposse/terraform-aws-s3-bucket/releases/tag/3.1.0
=> Use s3_object_ownership variable

modules/spacelift/admin-stack/child-stacks.tf, modules/spacelift/admin-stack/root-admin-stack.tf
- added missing description option
- Variable is defined, but never passed to the modules
n/a
=> Spacelift `admin-stack` `var.description`

modules/eks/karpenter/karpenter-crd-upgrade
- [eks/karpenter] Script to update Karpenter CRDs
- Upgrading Karpenter to v0.28.0 requires updating CRDs, which is not handled by current Helm chart. This script updates them by modifying the existing CRDs to be labeled as being managed by Helm, then installing the `karpenter-crd` Helm chart.
- Karpenter [CRD Upgrades](https://karpenter.sh/docs/upgrade-guide/#custom-resource-definition-crd-upgrades)
=> [eks/karpenter] Script to update Karpenter CRDs

modules/eks/storage-class/README.md, modules/eks/storage-class/context.tf, modules/eks/storage-class/main.tf, modules/eks/storage-class/outputs.tf, modules/eks/storage-class/provider-helm.tf, modules/eks/storage-class/providers.tf, modules/eks/storage-class/remote-state.tf, modules/eks/storage-class/variables.tf, modules/eks/storage-class/versions.tf
- Initial implementation of `eks/storage-class`
- Until now, we provisioned StorageClasses as a part of deploying [eks/ebs-controller](https://github.com/cloudposse/terraform-aws-components/blob/ba309ab4ffa96169b2b8dadce0643d13c1bd3ae9/modules/eks/ebs-controller/main.tf#L20-L56) and [eks/efs-controller](https://github.com/cloudposse/terraform-aws-components/blob/ba309ab4ffa96169b2b8dadce0643d13c1bd3ae9/modules/eks/efs-controller/main.tf#L48-L60). However, with the switch from deploying "self-managed" controllers to EKS add-ons, we no longer deploy `eks/ebs-controller` or `eks/efs-controller`. Therefore, we need a new component to manage StorageClasses independently of controllers.
- #723
=> [eks/storage-class] Initial implementation

modules/account-map/main.tf
* filter out “SUSPENDED” accounts  (aka accounts in waiting period for termination) for `account-map` component
* suspended account cannot be used, so therefore it should not exist in the account-map
* allows for new _active_ accounts with same exact name of suspended account to exists and work with `account-map`
* n/a
=> feat: filter out “SUSPENDED” accounts for account-map

modules/aws-saml/modules/okta-user/main.tf, modules/datadog-private-location-ecs/main.tf
- Added `enabled` parameter for `modules/aws-saml/modules/okta-user/main.tf` and `modules/datadog-private-location-ecs/main.tf`
- No support for disabling the creation of the resources
=> Added Enabled Parameter to aws-saml/okta-user and datadog-synthetics-private-location

modules/eks/cluster/README.md, modules/eks/cluster/addons.tf, modules/eks/cluster/eks-node-groups.tf, modules/eks/cluster/fargate-profiles.tf, modules/eks/cluster/main.tf, modules/eks/cluster/remote-state.tf
- Proper handling of cold start and `enabled=false`
- Fixes #797 
- Supersedes and closes #798 
- Cloud Posse standard requires error-free operation and no resources created when `enabled` is `false`, but previously this component had several errors
=> [eks/cluster] Proper handling of cold start and enabled=false

modules/eks/cluster/README.md, modules/eks/cluster/variables.tf, modules/eks/karpenter/main.tf
- [eks/karpenter] use Instance Profile name from EKS output
- Clarify recommendation and fix defaults regarding deploying add-ons to managed node group
- Bug fix: Karpenter did not work when legacy mode disabled
- Originally we expected to use Karpenter-only clusters and the documentation and defaults aligned with this. Now we recommend all Add-Ons be deployed to a managed node group, but the defaults and documentation did not reflect this.
=> Karpenter bugfix, EKS add-ons to mangaed node group

docs/upgrade-guide.md
- Added a placeholder file for `docs/upgrade-guide.md` with a basic explanation of what is to come
- With #811 we moved the contents of this upgrade-guide file to the individual component. We plan to continue adding upgrade guides for individual components, and in addition, create a higher-level upgrade guide here
- However, the build steps for refarch-scaffold expect `docs/upgrade-guide.md` to exist and are failing without it. We need a placeholder until the `account-map`, etc changes are added to this file
- Example of failing release: https://github.com/cloudposse/refarch-scaffold/actions/runs/5885022872
=> Placeholder for `upgrade-guide.md`

modules/spacelift/admin-stack/child-stacks.tf, modules/spacelift/admin-stack/root-admin-stack.tf
- set alternate git provider blocks to filter under `settings.spacelift`
- Debugging GitLab support specifically 
- These settings should be defined under `settings.spacelift`, not as a top-level configuration
- n/a
=> Spacelift Alternate git Providers

modules/eks/alb-controller/CHANGELOG.md, modules/eks/alb-controller/distributed-iam-policy.tf, modules/eks/alb-controller/main.tf
- Change name of local variable from `distributed_iam_policy_overridable` to `overridable_distributed_iam_policy`
- Cloud Posse style guide requires `overridable` as prefix, not suffix.
=> Fix naming convention of overridable local variable

modules/aws-config/README.md, modules/aws-config/main.tf
* Upgrade aws-config and conformance pack modules to 1.1.0
* They're outdated.
=> Upgrade aws-config and conformance pack modules to 1.1.0

modules/aws-sso/CHANGELOG.md, modules/aws-sso/README.md, modules/aws-sso/default.auto.tfvars, modules/aws-sso/policy-Identity-role-TeamAccess.tf, modules/aws-sso/providers.tf
For `aws-sso`:
- Fix root provider, improperly restored in #740 
- Restore `SetSourceIdentity` permission inadvertently removed in #740
- When deploying to `identity`, `root` provider did not reference `root` account
- Likely unintentional removal due to merge error
- #740 
- #738
=> [aws-sso] Fix root provider, restore `SetSourceIdentity` permission

modules/aurora-mysql-resources/provider-mysql.tf, modules/aurora-mysql/ssm.tf, modules/aurora-postgres-resources/provider-postgres.tf, modules/aurora-postgres/ssm.tf
- Set `module.context` to `module.cluster` across all resources
- Only set parameter for replica if cluster size is > 0
- `enabled: false` support
- Missing tags for SSM parameters for cluster attributes
- Serverless clusters set `cluster_size: 0`, which will break the SSM parameter for replica hostname (since it does not exist)
- Support enabled false for `aurora-*-resources` components
- n/a
=> Aurora Upstream: Serverless, Tags, Enabled: False

modules/tgw/README.md, modules/tgw/spoke/README.md, modules/tgw/spoke/main.tf, modules/tgw/spoke/variables.tf
- Added FAQ to the TGW upgrade guide for replacing attachments
- Added note about destroying TGW components
- Added option to not create TGW propagation and association when connecting an alternate VPC
- When connecting an alternate VPC in the same region as the primary VPC, we do not want to create a duplicate TGW propagation and association
- n/a
=> TGW FAQ and Spoke Alternate VPC Support

modules/aurora-postgres/README.md, modules/aurora-postgres/cluster-regional.tf, modules/aurora-postgres/variables.tf
- Add scaling configuration variables for both Serverless and Serverless v2 to `aurora-postgres`
- Update `aurora-postgres` README
- Support both serverless options
- Add an explanation for how to configure each, and where to find valid engine options 
- n/a
=> Aurora Postgres Engine Options

modules/tgw/spoke/README.md, modules/tgw/spoke/main.tf, modules/tgw/spoke/variables.tf
- Return the transit gateway association and propagation creation to all `tgw/spoke` deployments
- We conditional set the creation for alternate VPCs in the same region. However, all VPCs do need a separate transit gateway association and propagation in the network account, which is what this setting is enabling.
- n/a
=> TGW Spoke Association and Propagation

modules/eks/cluster/CHANGELOG.md, modules/eks/cluster/README.md, modules/eks/cluster/addons.tf, modules/eks/cluster/main.tf, modules/eks/cluster/remote-state.tf, modules/eks/cluster/variables.tf
Changes to `eks/cluster`:
- Timeouts for Add-Ons are now honored (they were being ignored)
- If you supply a service account role ARN for an Add-On, it will be used, and
no new role will be created. Previously it was used, but the component created
a new role anyway.
- The EKS EFS controller add-on cannot be deployed to Fargate, and enabling it
along with `deploy_addons_to_fargate` will no longer attempt to deploy EFS
to Fargate. Note that this means to use the EFS Add-On, you must create
a managed node group. Track the status of this feature with [this issue](https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/1100).
- If you are using an old VPC component that does not supply `az_private_subnets_map`,
this module will now use the older the `private_subnet_ids` output.
- The EKS …
=> [eks/cluster] Bug fixes for add-ons

modules/eks/actions-runner-controller/charts/actions-runner/templates/runnerdeployment.yaml
- Add `{{ .Values.release_name }}` to Docker creds kubernetes secret
- When deploying multiple runners, each runner should have its own secrets. Otherwise, deployment fails with the following:
```bash
│ Error: release infra-runner-amd64-medium failed, and has been rolled back due to atomic being set: failed to create resource: secrets "regcred" already exists
│
│   with module.actions_runner["infra-runner-amd64-medium"].helm_release.this[0],
│   on .terraform/modules/actions_runner/main.tf line 65, in resource "helm_release" "this":
│   65: resource "helm_release" "this" {
│
╵
╷
│ Error: release infra-runner-amd64-large failed, and has been rolled back due to atomic being set: no Secret with the name "regcred" found
│
│   with module.actions_runner["infra-runner-amd64-large"].helm_release. …
```
=> Bug fix: Multiple `eks/arc` Runners with Docker Login

modules/vpc-flow-logs-bucket/README.md, modules/vpc-flow-logs-bucket/main.tf
- update the `vpc-flow-logs-s3-bucket` module to 1.0.1 in `vpc-flow-logs-bucket`
- the new aws provider complains about iam policies
=> chore: update vpc flow logs bucket to 1.0.1

deprecated/eks/efs-controller/main.tf
- The `eks/efs-controller` is now deprecated and replaced by `eks/storage-class`, yet this is a simple fix.
- Conditionally get the `efs` ID only if the component is enabled
- If no condition is set, the output lookup will fail if EFS is not deployed (with both `enabled: false`)
```
Planning failed. Terraform encountered an error while generating this plan.
╷
│ Error: Unsupported attribute
│ 
│   on main.tf line 53, in module "efs_controller":
│   53:           fileSystemId     = module.efs.outputs.efs_id
│     ├────────────────
│     │ module.efs.outputs is object with 1 attribute "efs_host"
│ 
│ This object does not have an attribute named "efs_id".
╵
[01HCJ1RR2820WGGN828BCZPDTK] Unexpected exit code when planning changes: 1
```
=> Handle `enabled: false` with Deprecated `eks/efs-controller`

modules/aurora-mysql/README.md, modules/aurora-mysql/ssm.tf
- Corrected variable names for the `aurora-mysql` component
- `var.cluster_size` is used in `aurora-postgres`, not `aurora-mysql`. This should be `var.mysql_cluster_size`
- The Readme referred to incorrect variable names
- JBI-153
=> Variable names for `aurora-mysql`

modules/eks/cluster/README.md
- Fixed link in the `eks/cluster` README
- Updated End Of Life table for `amazon-eks`
- Added reference for Kubernetes project itself
- Extra `()` were included by mistake
- Updated end of life documentation
- n/a
=> Updated `eks/cluster` README EOL Table

modules/spacelift/admin-stack/README.md, modules/spacelift/admin-stack/remote-state.tf, modules/spacelift/admin-stack/variables.tf
- add variable `spacelift_spaces_component_name`
- allows configuration of alternative names and implementations of
`spacelift/spaces`
=> ref: spacelift/admin-stack supports custom spaces components

modules/eks/cluster/remote-state.tf
- Include `environment` in map key when iterating through `var.allow_ingress_from_vpc_accounts` for `eks/cluster`
- VPC accounts with the same `stage` and (optional) `tenant` but different `environments` in `var.allow_ingress_from_vpc_accounts` will otherwise have the same map key, and Terraform will fail
- n/a
=> Allow VPC Ingress from Multiple Regions in Same Stage for `eks/cluster`

modules/eks/external-secrets-operator/README.md, modules/eks/external-secrets-operator/additional-iam-policy-statements.tf, modules/eks/external-secrets-operator/main.tf, modules/eks/external-secrets-operator/remote-state.tf
- Update module versions
- Add optional override for additional policies for `eks/external-secrets-operator`
- We may want to grant additional access to the operator. With the override pattern, we can grant whatever we need for specific use-case and avoid conflicts with upstream
- override pattern reference: https://github.com/cloudposse/terraform-aws-components/blob/main/modules/aws-teams/additional-policy-map.tf
=> `eks/external-secrets-operator` Overridable Additional Policy Statements

modules/datadog-synthetics/CHANGELOG.md, modules/datadog-synthetics/README.md, modules/datadog-synthetics/catalog/synthetics/examples/browser-test.yaml, modules/datadog-synthetics/main.tf, modules/datadog-synthetics/outputs.tf, modules/datadog-synthetics/variables.tf, modules/tfstate-backend/README.md
- [datadog-synthetics] Accept Datadog API output as input
- [tfstate-backend] Add information to README about adjusting quotas
- Make it easy to use Datadog web API to create or edit tests and import them into Terraform
- Upgrade commonly hits default quota limit, resolved by requesting quota increase
- https://github.com/cloudposse/terraform-datadog-platform/pull/81
=> [datadog-synthetics] Accept Datadog API output as input

modules/datadog-monitor/catalog/monitors/lambda.yaml
All DD monitor names must be namespaced
Otherwise it will not deploy to a multi-stage env
=> All DD monitor names must be namespaced

modules/opsgenie-team/CHANGELOG.md, modules/opsgenie-team/README.md, modules/opsgenie-team/main.tf, modules/opsgenie-team/modules/escalation/main.tf, modules/opsgenie-team/outputs.tf, modules/opsgenie-team/variables.tf, modules/opsgenie-team/versions.tf
- Changes to `opsgenie-team`
- BREAKING CHANGE: `team` replaced with `team_options`
- Bugfix/breaking change: add members to teams unless explicitly instructed otherwise. Previously the default was to delete all members from the team. 
- The `team` input was not properly implemented, so maintaining compatibility is not desirable
- The point of the component is to create a team, and the team's name comes from the `name` input, not the `team` input, so the name of the input was confusing on more than one level
- The intended default was to manage team members via this component
=> [opgenie-team] Bugfix: add members to teams

modules/aws-shield/main.tf
- fixes typo in `aws-shield`
- so it will work
=> Fixes typo in aws-shield

modules/aws-shield/remote-state.tf
- `aws-shield` would fail plan if disabled
- allow workflows to disable `aws-shield` without failure
=> fix(aws-shield would fail plan if disabled)

modules/aws-shield/alb.tf
- fixes ternary type mismatch in `aws-shield`
- to fix plans
=> fixes type mismatch in aws-shiield ternary

modules/eks/karpenter/main.tf
Fix karpenter resources specification
var.resources not picked up by underlying chart
https://github.com/aws/karpenter/blob/00b2f4dc086723645f0f15e2c4dd549996eeaa07/charts/karpenter/values.yaml#L96-L110
```
√ . [cdb-core-gbl-identity-admins] (HOST) infrastructure ⨠ helm get values karpenter
USER-SUPPLIED VALUES:
aws:
enableENILimitedPodDensity: false
controller:
env:
- name: LEADER_ELECT
value: "false"
resources:
limits:
cpu: "1"
memory: 1536Mi
requests:
cpu: 800m
memory: 1536Mi
⧉  cdb (plat-use1-dev:karpenter)
√ . [cdb-core-gbl-identity-admins] (HOST) infrastructure ⨠ k get -o yaml pods | grep resources -A 6
resources:
limits:
cpu: "1"
memory: 1536Mi
requests:
cpu: 800m
memory: 1536Mi
```
=> fix: Karpenter resources

modules/aws-saml/modules/okta-user/main.tf, modules/aws-saml/modules/okta-user/outputs.tf
- Bugfix: `aws-saml` component without okta giving issue about not picking a member of the array since enabled flag was added with count in #805 
- deploy component whether or not okta is used
- #805
=> Bugfix: Okta Submodule in `aws-saml`

modules/ecs/main.tf
Currently the subnets of the alb are configured by `internal_enabled` variable which is at the var level. this means both albs are deployed to the same set of subnets, either public or private.
This PR changes that logic to deploy any loadbalancer with `internal_enabled` which is nested under the `alb_configuration.<LB_Name>` key to the appropriate subnet.
- alb subnets determined by `internal_enabled` flag on each LB
- ALBs are intended to be deployed based on it's configuration, e.g.:
```yaml
internal_enabled: false # (default value) # this now is the default incase not defined per LB below
alb_configuration:
public:
internal_enabled: false # redundant but means public LB in public subnets
route53_record_name: "*.public-platform"
private:
internal_enabled: true # specifies this should …
```
=> ECS Cluster ALB Subnet decision per ALB

modules/eks/cluster/CHANGELOG.md, modules/eks/cluster/main.tf
[eks/cluster]:
- Document migration from Karpenter-only to minimal managed node group
- Fix bug that can occur during migration
- Previously we recommended deploying EKS clusters with no managed node groups, deploying Karpenter to Fargate to manage all other nodes. We have since changed this recommendation based on issues with addons and high availability; we now recommend deploying a minimal managed node group (1 instance in each of 3 availability zones). Therefore, we want to provide documentation on why we changed our recommendation and how to make the recommended changes.
- The migration procedure uncovered a bug that would be triggered when an existing EKS cluster had no managed node groups. This is now fixed.
=> [eks/cluster] Document Migration to Managed Node Group. Bugfix.

modules/philips-labs-github-runners/README.md, modules/philips-labs-github-runners/context.tf, modules/philips-labs-github-runners/main.tf, modules/philips-labs-github-runners/modules/README.md, modules/philips-labs-github-runners/modules/webhook-github-app/README.md, modules/philips-labs-github-runners/modules/webhook-github-app/bin/update-app.sh, modules/philips-labs-github-runners/modules/webhook-github-app/main.tf, modules/philips-labs-github-runners/modules/webhook-github-app/variables.tf, modules/philips-labs-github-runners/modules/webhook-github-app/versions.tf, modules/philips-labs-github-runners/outputs.tf, modules/philips-labs-github-runners/providers.tf, modules/philips-labs-github-runners/remote-state.tf, modules/philips-labs-github-runners/templates/userdata_post_install.sh, modules/philips-labs-github-runners/variables.tf, modules/philips-labs-github-runners/versions.tf
- The [philips-labs/terraform-aws-github-runner](https://github.com/philips-labs/terraform-aws-github-runner) is a popular way to deploy scalable self-hosted GitHub Runners on AWS. This PR introduces a component to deploy those runners.
- This uses their default example as the basis of this component.
- When not using EKS and actions runner controller, we need a scalable way to use self-hosted GitHub runners. Currently, we use an ASG-based component. This is slower and less responsive to surges, furthermore, it scales down slower, resulting in higher operating costs.
* https://github.com/philips-labs/terraform-aws-github-runner
- The Philips lab module currently has support for yaml based multi-arch runners. This would fit nicely into the Cloud Posse Reference architecture with stacks and …
=> New Component: `philips-labs-github-runners`

modules/spacelift/worker-pool/iam.tf
- Added back local definition for `local.identity_account_name` for the `spacelift/worker-pool` component
- This value is used in the `iam.tf` policy
- Only `local.identity_account_id` should have been removed, not `local.identity_account_name`
- https://sweetops.slack.com/archives/C04NBF4JYJV/p1700604335106819
=> Return `local.identity_account_name` for `spacelift/worker-pool`

modules/spacelift/worker-pool/templates/user-data.sh
- Updated CLI command to log into docker in Spacelift Worker Pool user data
- Spacelift has updated the AWS CLI in their AMIs, creating a breaking change. This is a quote from Spacelift
> [...] you have a very good point about this being an unannounced breaking change. we’ll prepare an announcment today, and we’ll try to think about introducing semver into this process. sorry for the inconvenience.
- https://sweetops.slack.com/archives/C04NBF4JYJV/p1700606072243389
- https://sweetops.slack.com/archives/C04NBF4JYJV/p1700652828337319
- https://github.com/spacelift-io/spacelift-worker-image/releases/tag/1.0.0
=> fix: `spacelift/worker-pool` AMI User Data Docker Login

modules/aws-inspector2/README.md, modules/aws-inspector2/main.tf
- enables Inspector on Delegated Admin and Member accounts
- deployments would fail due to `invoking account not being enabled`
=> fix(inspector is now enabled on deploy)

modules/bastion/templates/user-data.sh
- removed volume mount steps from `bastion` userdata
- there is no additional volume or block storage attached to a bastion instance. So userdata would get stuck at this step and fail to complete.
```console
[  345.411338] cloud-init[2351]: waiting for device /dev/sdh
```
- https://sweetops.slack.com/archives/CDYGZCLDQ/p1701787882992429
=> fix: `bastion` userdata volume mount

mixins/github-actions-iam-policy/github-actions-iam-policy.tf
* Policy for any GHA Role to be defined
* Hardcoding means it can be tough to adjust as needed. this lets the stack configuration determine the policy
=> dynamic GHA role

modules/aurora-postgres-resources/README.md, modules/eks/github-actions-runner/CHANGELOG.md, modules/eks/github-actions-runner/README.md, modules/eks/github-actions-runner/context.tf, modules/eks/github-actions-runner/main.tf, modules/eks/github-actions-runner/outputs.tf, modules/eks/github-actions-runner/provider-helm.tf, modules/eks/github-actions-runner/provider-ssm.tf, modules/eks/github-actions-runner/providers.tf, modules/eks/github-actions-runner/remote-state.tf, modules/eks/github-actions-runner/runners.tf, modules/eks/github-actions-runner/variables.tf, modules/eks/github-actions-runner/versions.tf
- Add `eks/github-actions-runner` to deploy GitHub Action Runner Scale Sets
- [`aurora-postgres-resources`] Add/clarify documentation on PostgreSQL `GRANT`
- Official GitHub implementation of GitHub Action Runners self-hosted on Kubernetes
- Clear up some confusion experienced by a customer
- `actions-runner-controller` adopted by GitHub: [Announcement](https://github.com/actions/actions-runner-controller/discussions/2072)
- https://github.com/actions/actions-runner-controller/discussions/2775
- [Quickstart for Actions Runner Controller](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/quickstart-for-actions-runner-controller)
- Runner Scale Set Controller's Helm chart …
=> New component deploying GitHub Action Runner Scale Sets

modules/aws-backup/README.md, modules/aws-backup/main.tf, modules/aws-backup/outputs.tf, modules/aws-backup/remote-state.tf, modules/aws-backup/variables.tf
- pull latest additions for `aws-backup`
- Adding support for changing the destination vault 
- customer engagement
=> chore: upstream `aws-backup`

modules/eks/github-actions-runner/CHANGELOG.md, modules/eks/github-actions-runner/README.md
- [eks/github-actions-runner] Update documentation to explain about tools missing from runners
- Lack of common tools has caught people by surprise
- Official documentation stating that runners contain [no more packages than are necessary](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/about-actions-runner-controller#about-the-runner-container-image)
- Feature request asking for additional tools in [actions/actions-runner-controller discussions](https://github.com/actions/actions-runner-controller/discussions/3168)
- Feature request asking for additional tools in [GitHub community discussions](https://github.com/orgs/community/discussions/80868)
- [Dockerfile](https://github.com/actions/actions-runner-controller/blob/ …
=> [eks/github-actions-runner] Explain about tools missing from runners

modules/spacelift/admin-stack/README.md, modules/spacelift/admin-stack/child-stacks.tf, modules/spacelift/admin-stack/root-admin-stack.tf, modules/spacelift/admin-stack/variables.tf
- Change the resource type used for `var.context_attachments` to a list of strings rather than a set of strings
- The terraform logic for Spacelift stack attachments (found in attachments.tf) uses a terraform for-loop in the two-symbol form to retrieve the index in each iteration of the loop. This leads to an error as the type of the variables used for these attachments is set(string), which does not support two-symbol loops.
- https://github.com/cloudposse/terraform-spacelift-cloud-infrastructure-automation/pull/160
- resolves https://github.com/cloudposse/terraform-aws-components/issues/939
=> fix `spacelift/admin-stack`: changed resource type from set to list

modules/aws-ssosync/README.md
- changed image links to raw urls for `aws-ssosync` component README
- When the docs.cloudposse website tries to render docusarus from this README, the image is not found. Instead we can use the raw URL to the image that will work for both GitHub and for docusarus
- follow up to #941 
- resolves this failure (private repo): https://github.com/cloudposse/refarch-scaffold/actions/runs/7351459617/job/20014834647
```console
Error: Image content/components/library/aws/aws-ssosync/docs/img/admin_sdk.png used in content/components/library/aws/aws-ssosync/README.md not found.
at async Promise.all (index 0)
Error:  Client bundle compiled with errors therefore further build is impossible.
make: *** [Makefile:16: build] Error 1
Error: Process completed with exit code 2.
```
=> fix: image links for website

modules/ecs/main.tf
- ECS Cluster bugfix if optional deep nested kv is empty we shouldn't try to add the additional certs
- bugfix
=> bugfix: `ECS` additional_certs is empty

modules/lambda/README.md, modules/lambda/main.tf, modules/lambda/variables.tf
- Adds changes from our main_overrides.tf to simplify the ability to deploy a lambda through CICD using SSM Parameter store and an s3 bucket
Simplify deployment process
=> Lambda Component Support CICD

modules/philips-labs-github-runners/templates/userdata_post_install.sh
- update post install for philips labs component to add
- AWS
- GH
- Node
- Common tools required by workflows
- Node version matches that of a Github Ubuntu latest worker
- https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
=> `philips-labs-github-runners` component add `node`, `aws`, `gh` cli

modules/ecs-service/README.md, modules/ecs-service/main.tf, modules/ecs-service/remote-state.tf, modules/ecs-service/variables.tf
- efs volume lookup support for ecs
- Its a pain to copy and lookup EFS ID's. This PR allows lookups with the `efs_component_volumes` which allows remote state lookup for EFS ID's and can merge that in to the hardcoded EFS Volumes
=> EFS Volume Lookup support for `ecs-service`

.github/workflows/auto-release.yml, .github/workflows/bats.yml
* Use `cloudposse/github-action-auto-release` in `auto-release.yaml` workflow
* Solve old nodejs warning
* Reduce duplication of code
=> Consolidate auto-release workflow

modules/ecs-service/github-actions-iam-policy.tf
- add `ecs:TagResource` permission to policies
- changes to ECS policies mean that Task definitions can't have tagging
details without a policy update
- [Tag Resource permissions in
ECS](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-account-settings.html#tag-resources-setting)
=> chore: ecs-service policies should allow tagging now

modules/spa-s3-cloudfront/CHANGELOG.md, modules/spa-s3-cloudfront/lambda_edge.tf
* [spa-s3-cloudfront] Fix preview environments
* Preview envs required `x-forwarded-host` that is set by paywall lambdas. When the paywall is disabled, the preview still needs to work correctly.
=> [spa-s3-cloudfront] Fix preview enviornments

modules/ecs-service/systems-manager.tf
- Only set `key_id` for `aws_ssm_parameter` when the type is "SecureString"
- With other types Terraform will pass but will constantly suggest adding the `key_id`
- https://github.com/hashicorp/terraform-provider-aws/issues/21095
=> Fix: `ecs-service` perma-drift for `key_id`

modules/ecs-service/main.tf, modules/ecs-service/outputs.tf
- S3 mirroring should be a conditional statement for additional features
- Missed conditionals which prevent's backwards compatibility
#997
=> hotfix: `ecs-service` S3 Mirroring conditional

modules/eks/actions-runner-controller/README.md, modules/eks/datadog-agent/README.md, modules/github-runners/README.md, modules/tfstate-backend/README.md
- move the end of `:::` blocks
- prettier tries to flow them into the paragraph, which causes docusaurus to
not close blocks
- see example of error here: https://docs.cloudposse.com/components/library/aws/tfstate-backend/
=> fix: prettier format errors

modules/ecs-service/CHANGELOG.md, modules/ecs-service/README.md, modules/ecs-service/main.tf, modules/ecs-service/outputs.tf, modules/ecs-service/systems-manager.tf
ECS Service Upstream for better support of partial task definition.
* Fixes issue with bad merges on s3 task definition
* Map_secrets not being updated
=> `ecs-service` better task definition merging

modules/eks/actions-runner-controller/README.md
Add readme section for dockerhub auth
* docs
https://github.com/cloudposse/terraform-aws-components/pull/726/files#diff-c8b978e7ac4c539b35f601c183d45b20589834e067becae2bc18731a23069b65
=> EKS: `actions-runner-controller` readme update for dockerhub auth

modules/tfstate-backend/README.md, modules/tfstate-backend/iam.tf
- `tfstate-backend`:
- Update documentation to recommend explicitly configuring SuperAdmin access when convenient
- Update component to filter out duplicate "allowed principal" when current user is explicitly allowed
- The current reference architecture allows both SuperAdmin and `root-admin` to administer most "cold-start" components after cold start has been completed. However, without these changes, if `root-admin` updated `tfstate-backend`, SuperAdmin would lose access to Terraform state.
=> [tfstate-backend] Recommend explicit configuration of SuperAdmin

modules/eks/echo-server/charts/echo-server/templates/deployment.yaml
- Fix setting resources limits and request via chart inputs
- Previously, the Deployment template incorrectly accessed the chart values for resource limits and requests, making them impossible to set.
Echo-server can serve other purposes than just verifying end-to-end cluster configuration. Among them, by setting high resource requests, it can be used to trigger cluster autoscaling. However, that requires resource requests settings to be able to be configured.
=> [eks/echo-server] Fix resource settings via chart inputs

modules/api-gateway-rest-api/remote-state.tf
- Set default value for remote `acm` component reference in the `api-gateway-rest-api` component
- When the `acm` component doesnt exist, we want to use the value from `dns-delegated` instead like this
```hcl
root_domain = coalesce(module.acm.outputs.domain_name, join(".", [
module.this.environment, module.dns_delegated.outputs.default_domain_name
]), module.dns_delegated.outputs.default_domain_name)
```
- However, if `acm` doesnt exist, `module.acm.outputs` will be null:
```console
│ Error: Attempt to get attribute from null value
│
│   on main.tf line 5, in locals:
│    5:   root_domain = coalesce(module.acm.outputs.domain_name, join(".", [
│     ├────────────────
│     │ module.acm.outputs is null
│
│ This value is null, so it does not have any attributes.
╵
exit status 1
```
- n/a
=> fix: `api-gateway-rest-api` Default Value

modules/aurora-postgres/README.md, modules/aurora-postgres/main.tf, modules/aurora-postgres/outputs.tf, modules/aurora-postgres/variables.tf
* Adds passing additional security group names to the `aurora-postgres` component to support additional inbound rules into the resulting aurora PG cluster. 
* This is needed when you have external systems that you want to have access to the DB cluster that are not accounted for by EKS and you don't want to be overly permissive with allowing a the full CIDR Block. In our case, we're using AWS DMS and need that to be able to communicate with one of our DB clusters. 
* N/A
=> feat(aurora-pg): allow passing extra SGs to allow

modules/elasticache-redis/main.tf, modules/elasticache-redis/modules/redis_cluster/main.tf, modules/elasticache-redis/modules/redis_cluster/variables.tf, modules/elasticache-redis/variables.tf
- Upgrade `elasticache-redis` module version in the `elasticache-redis` component
- Adds three new variables from the module; `create_parameter_group`, `parameter_group_name`, and `multi_az_enabled`
- Use the latest module version with the component
- New variables were added in module version `1.0.0` https://github.com/cloudposse/terraform-aws-elasticache-redis/releases/tag/1.0.0
=> chore: bump elasticache-redis module version

modules/elasticache-redis/modules/redis_cluster/variables.tf
- Add missing variable `multi_az_enabled`
- This variable should have been included in https://github.com/cloudposse/terraform-aws-components/pull/1040
- https://github.com/cloudposse/terraform-aws-components/pull/1040
- https://github.com/cloudposse/terraform-aws-elasticache-redis/blob/caabd7ea05a5809cc71383b34a0556ffe76a6d5a/variables.tf#L127-L131
=> fix: add missing multi_az_enabled variable

modules/rds/README.md, modules/rds/outputs.tf, modules/rds/systems-manager.tf
- Add output for KMS key alias
- Update SSM naming convention
- Useful output for KMS key references
- When `var.name` doesnt exist, this path includes `null`. We want to optionally support setting `var.attributes` without a `var.name`
- customer engagement
=> fix(`rds`): Corrected SSM Paths for Non Existent `var.name`

.github/workflows/update-changelog.yml
* Run update-changelog on public runners
* There is no reason to use self-hosted for this workflow. 
* We do not have configured self-hosted runners in that repo
=> Run update-changelog on public runners

modules/vpc/main.tf
Update `dynamic-subnets` module version to fix issue https://github.com/cloudposse/terraform-aws-components/issues/1047
Version 2.3.0 of `dynamic-subnets` does not support the new opt-in Melbourne region.
This change in `utils` module adds support for Melbourne (amongst other regions) - https://github.com/cloudposse/terraform-aws-utils/pull/26 
And this is the version of `dynamic-subnets` where it was updated to use the updated `utils` module.  https://github.com/cloudposse/terraform-aws-dynamic-subnets/releases/tag/2.4.0 
This PR closes #1047
=> [vpc] update dynamic-subnet module version

modules/eks/actions-runner-controller/README.md, modules/eks/actions-runner-controller/charts/actions-runner/Chart.yaml, modules/eks/actions-runner-controller/charts/actions-runner/templates/runnerdeployment.yaml, modules/eks/actions-runner-controller/charts/actions-runner/values.yaml, modules/eks/actions-runner-controller/main.tf, modules/eks/actions-runner-controller/resources/values.yaml, modules/eks/actions-runner-controller/variables.tf
For `eks/actions-runner-controller`
- Add ability to dynamically annotate pods once they start a job
- Add ability to specify runner pod affinities and anti-affinities
- Deprecate `storage` in favor of `docker_storage` to configure how much disk space to allocate for the Docker daemon
- Miscellaneous cleanups of inputs and chart 
- Allow idle runners to be evicted by Karpenter for purposes of node consolidation, while preventing running runners from being interrupted
- Allow runners to have more control over where they are placed
- The term "storage" is too vague, and could reasonably be expected to configure the worker storage, but in fact it only configures the Docker storage. (Storage size for the optional PVC is still hardcoded at 100Gi.)
- Make chart a bit more readable and …
=> [eks/actions-runner-controller] Add ability to dynamically annotate pods once they start a job

modules/eks/cluster/CHANGELOG.md, modules/eks/cluster/main.tf
- Fix "Invalid count argument" argument when creating new cluster
- Clusters could not be created from scratch
- Introduced in #1033
=> [eks/cluster] Bugfix: invalid count argument when creating new cluster

.github/workflows/bats.yml
* Replace `pull_request_target` by `pull_request`
* Use `terraform 1` for bats
* Improve security 
* test-harness support terraform and opentofu, use terraform for bats
=> Update bats workflow

modules/spa-s3-cloudfront/README.md, modules/spa-s3-cloudfront/main.tf
- updated `cloudposse/cloudfront-s3-cdn/aws` in `spa-s3-cloudfront`
- updated `cloudposse/acm-request-certificate/aws` in `spa-s3-cloudfront`
- essential bugfixes. Private cloudfront buckets do not work without
the bucket policy fix from `0.95.0` of the cloudfront module.
- see [Cloudfront Bucket Policy
Fix](https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/pull/311)
=> chore: update modules for spa-s3-cloudfront

modules/aurora-postgres/README.md, modules/aurora-postgres/cluster-regional.tf, modules/aurora-postgres/variables.tf
The CloudPosse RDS cluster module https://github.com/cloudposse/terraform-aws-rds-cluster has these backup configurations that would be helpful to have!
1. Allows me to set backup configurations
2. Without these inputs, the cluster is forced to use the default configs from the module
3. Allows me to set these variable values to `null` or empty when I don't want any backing up happening
4. Without these inputs to set it as empty values, there's a conflict when using RDS clusters with AWS Backup plans because the RDS resource maintains its backup values, while AWS Backup plans wants other values.
- CloudPosse's RDS module
- 
- AWS Backup conflict with default backup values unless explictly set https://github.com/hashicorp/terraform-provider-aws/issues/33465
=> feat(aurora-postgres): backup configs

modules/eks/external-secrets-operator/README.md, modules/eks/external-secrets-operator/main.tf, modules/eks/external-secrets-operator/variables.tf
* adds support for decrypting KMS keys by alias
* it's a pain to lookup AWS KMS keys by arn or ID. so this adds alias support
=> External-Secrets: Add variable for decrypting aliased KMS keys

modules/eks/cluster/CHANGELOG.md, modules/eks/cluster/modules/node_group_by_az/main.tf
- Update `eks/cluster` to use [eks-node-group v3](https://github.com/cloudposse/terraform-aws-eks-node-group/releases/tag/3.0.0)
- Support Amazon Linux 2023 on EKS
- Other bug fixes and improvements
- https://github.com/cloudposse/terraform-aws-eks-node-group/releases/tag/3.0.0
=> Update eks/cluster to use eks-node-group v3

modules/eks/alb-controller/CHANGELOG.md, modules/eks/cluster/CHANGELOG.md, modules/eks/cluster/modules/node_group_by_az/main.tf
- [eks/cluster] Update `cloudposse/eks-node-group/aws` to v3.0.1
- Fix failure to create userdata for AL2 and Windows when needed
- https://github.com/cloudposse/terraform-aws-eks-node-group/pull/187
=> [eks/cluster] Update eks-node-group to v3.0.1

modules/eks/loki/main.tf
- Removed `compact` from the `eks/loki` component list of objects for schema config
- Fix terraform when one of this lists isnt defined
- n/a
=> fix(`eks/loki`): Remove Unnecessary `compact`

modules/eks/actions-runner-controller/CHANGELOG.md, modules/eks/actions-runner-controller/README.md, modules/eks/actions-runner-controller/charts/actions-runner/Chart.yaml, modules/eks/actions-runner-controller/charts/actions-runner/templates/horizontalrunnerautoscaler.yaml, modules/eks/actions-runner-controller/charts/actions-runner/templates/runnerdeployment.yaml, modules/eks/actions-runner-controller/charts/actions-runner/values.yaml, modules/eks/actions-runner-controller/main.tf, modules/eks/actions-runner-controller/outputs.tf, modules/eks/actions-runner-controller/resources/values.yaml, modules/eks/actions-runner-controller/variables.tf
- Add support for [scheduled overrides](https://github.com/actions/actions-runner-controller/blob/master/docs/automatically-scaling-runners.md#scheduled-overrides) of Runner Autoscaler min and max replicas.
- Add option `tmpfs_enabled` to have runners use RAM-backed ephemeral storage (`tmpfs`, `emptyDir.medium: Memory`) instead of disk-backed storage.
- Add `wait_for_docker_seconds` to allow configuration of the time to wait for the Docker daemon to be ready before starting the runner.
- Enhance the ability to have the runner Pods add annotations to themselves once they start running a job.
- Previously, `syncPeriod`, which sets the period in which the controller reconciles the desired runners count, was set to 120 seconds in `resources/values.yaml`. This setting has been removed, …
=> [eks/actions-runner-controller] Multiple bug fixes and enhancements

modules/eks/actions-runner-controller/CHANGELOG.md, modules/eks/actions-runner-controller/charts/actions-runner/Chart.yaml, modules/eks/actions-runner-controller/charts/actions-runner/templates/runnerdeployment.yaml, modules/eks/karpenter-node-pool/CHANGELOG.md, modules/eks/karpenter/CHANGELOG.md
-  Fix misconfigured document separators in Helm chart template
- Runner Deployment manifest would be malformed if not using `running_pod_annotations`
- Introduced in #1075
=> [eks/actions-runner-controller] Fix misconfigured document separators in Helm chart template

modules/eks/idp-roles/charts/idp-roles/Chart.yaml, modules/eks/idp-roles/charts/idp-roles/templates/clusterrole-reader-extra.yaml, modules/eks/idp-roles/charts/idp-roles/templates/clusterrole-reader.yaml, modules/eks/idp-roles/charts/idp-roles/templates/clusterrolebinding-reader.yaml, modules/eks/idp-roles/charts/idp-roles/values.yaml
* Added `reader` role for `eks/idp-roles`
* Required for dynamic terraform roles to read k8s resources
* https://github.com/cloudposse/infra-live/actions/runs/10146129540/job/28057016517
=> EKS IDP roles added reader

modules/account-map/README.md, modules/account-map/dynamic-roles.tf, modules/account-map/modules/iam-roles/main.tf, modules/account-map/modules/iam-roles/outputs.tf
* Support  terraform dynamic roles `dns_terraform_role_arn`, `audit_terraform_role_arn`, `identity_terraform_role_arn`
* Fix but in when `team_roles_stacks` does not have components defined
* Some components like `dns-deletegate` use `dns_terraform_role_arn`, `audit_terraform_role_arn`, `identity_terraform_role_arn` in `provider.tf`
In the case of gitops, the planner role can not assume an `apply` dynamic role. 
* Thats expected case for all `non gbl` accounts
* https://github.com/cloudposse/infra-live/actions/runs/10146129540/job/28119365151
* https://github.com/cloudposse/terraform-aws-components/blob/main/modules/dns-delegated/providers-dns-primary.tf#L11
=> Fix account map special accounts like  dns, identity support dynamic roles

modules/spacelift/spaces/README.md, modules/spacelift/spaces/main.tf, modules/spacelift/spaces/variables.tf
- Upgrade the Spacelift policies module to version 1.7.0 following the PR https://github.com/cloudposse/terraform-spacelift-cloud-infrastructure-automation/pull/183
- Add support for allowing using file path as the source of a Spacelift policy in addition to the current inline body and URLs
PR from the Spacelift module https://github.com/cloudposse/terraform-spacelift-cloud-infrastructure-automation/pull/183
=> feat(spacelift): support for local files for policies

deprecated/eks/karpenter-provisioner/README.md, modules/account/README.md, modules/auth0/tenant/README.md, modules/aws-config/README.md, modules/aws-sso/README.md, modules/dns-primary/README.md, modules/ecr/README.md, modules/eks/actions-runner-controller/CHANGELOG.md, modules/eks/cluster/CHANGELOG.md, modules/eks/cluster/README.md, modules/eks/datadog-agent/README.md, modules/eks/karpenter/CHANGELOG.md, modules/eks/karpenter/README.md, modules/github-runners/README.md, modules/network-firewall/README.md, modules/spacelift/README.md, modules/tfstate-backend/README.md
- Replace all Docusarus style admonitions with GitHub style admonitions
- We now can provide the GH style here and have the docs site convert the format into Docusarus style
- DEV-2453
- Required by https://github.com/cloudposse/docs/pull/642
=> Replace Admonition Style

modules/tfstate-backend/README.md, modules/tfstate-backend/iam.tf, modules/tfstate-backend/variables.tf
- fix(tfstate-backend): cold-start regression
- chore(tfstate-backend): update cold-start reqs
- tfstate cold-start had a regression bug that prevents an admin from using
the bucket/dynamodb
- [As reported in discussions](https://github.com/orgs/cloudposse/discussions/14)
=> fix: tfstate-backend cold-start regression

modules/memorydb/README.md, modules/memorydb/context.tf, modules/memorydb/main.tf, modules/memorydb/outputs.tf, modules/memorydb/providers.tf, modules/memorydb/remote-state.tf, modules/memorydb/variables.tf, modules/memorydb/versions.tf
- add component for memorydb module
- new module: [terraform-aws-memorydb](https://github.com/cloudposse/terraform-aws-memorydb)
=> feat: memorydb component

modules/eks/external-secrets-operator/main.tf
- Add the exact AWS SSM Parameter Store path for IAM permissions
- When using the `find.path` value, ESO will begin the traversal at the exact path defined.
- `ssm:GetParametersByPath` needs permission to the "root" path, eg `arn:aws:ssm:us-west-2:123456789012:parameter/app`
- https://external-secrets.io/latest/guides/getallsecrets/#searching-only-in-a-given-path
=> Add explicit parameter store path

.github/workflows/update-changelog.yml
* Fix modules path from `components/terraform` to `modules`
* It seems that `components/terraform` was testing value. In actual repo components are in `modules` directory
* DEV-2556 Investigate release issues with terraform-aws-components
=> Fix Update changelog workflow

modules/account-settings/README.md, modules/account-settings/budgets.tf
* Upgrades `terraform-aws-budgets` submodule usage in account-settings to 0.5.1
* This enables passing `subscriber_email_addresses` to budgets for receiving emails
* See fix in https://github.com/cloudposse/terraform-aws-budgets/pull/51
=> chore(account-settings): upgrades budgets child-module to 0.5.1

modules/site-to-site-vpn/README.md, modules/site-to-site-vpn/main.tf
Bumps VPN Module version to `1.3.1`
Includes a bugfix for when TGW is enabled.
- https://github.com/cloudposse/terraform-aws-vpn-connection/pull/51
=> update `site-to-site-vpn` module version

modules/site-to-site-vpn/README.md, modules/site-to-site-vpn/main.tf, modules/site-to-site-vpn/variables.tf
- Couple issues remained
- `null` variable (when set to `nullable=false`)
- misnamed module
- Bugfixes
#1144
=> upstream fixes for site-to-site-vpn

modules/runs-on/README.md
- Remove unclosed / unused summary
- This is breaking the cloudposse/docs release pipelines
- https://github.com/cloudposse/docs/actions/runs/11380845724
=> fix: Runs-On README

modules/dns-delegated/README.md
- Remove suggestion from README that it can be deployed regionally
- Add details and references about using `dns-delegated` and `dns-primary`
- Old information was wrong and lacking in detail, causing confusion
=> [dns-delegated] Fix README.md to remove suggestion of deploying regionally

modules/elasticache-redis/README.md, modules/elasticache-redis/main.tf, modules/elasticache-redis/modules/redis_cluster/main.tf, modules/elasticache-redis/modules/redis_cluster/variables.tf
- add engine input for valkey support
- Valkey is far cheaper than redis
<details><summary>Notes</summary>
- Design options
1. Add a new key to `local.cluster_attributes` and add a variable to the component, default it to `redis`, and pass as an argument to the module as-is
- We could shy away from the pattern to using `engine = var.engine` in the `local`.
1. Allow `var.redis_clusters` to supply `engine` with a default for `redis` and pass to module as-is
1. Same as option 2 but allow `local.cluster_attributes` to overwrite it
- This might be best of both worlds however no other argument does this so it would be breaking the pattern
- Went with option 2 so the argument isn't a new requirement for everyone and it doesn't break consistency
</details>
- …
=> feat(elasticache-redis): add engine input for valkey support
