- .dockerignore
- README.md
- codefresh.yml
* Update `README` to CloudPosse standard `README.md` format
* Standard documentation
* Consistency
> Update `README` to CloudPosse standard `README.md` format

- aws/root-dns/parent-audit-ns.tf
- aws/root-dns/parent-dev-ns.tf
- aws/root-dns/parent-local-ns.tf
- aws/root-dns/parent-prod-ns.tf
- aws/root-dns/parent-staging-ns.tf
- aws/root-dns/parent-testing-ns.tf
* Disable creation NS record if NS servers variable is empty
* Not all organization really need DNS zone
> Fix root dns

- aws/iam/audit.tf
- aws/iam/dev.tf
- aws/iam/prod.tf
- aws/iam/staging.tf
- aws/iam/testing.tf
Require MFA on all AWS accounts
Better security
> Require MFA on all AWS accounts

- aws/backing-services/elasticsearch.tf
- aws/eks-backing-services-peering/main.tf
- aws/eks-backing-services-peering/outputs.tf
- aws/eks-backing-services-peering/terraform.tfvars.example
- aws/eks-backing-services-peering/variables.tf
- aws/eks/eks.tf
- aws/eks/kubectl.tf
- aws/eks/main.tf
- aws/eks/outputs.tf
- aws/eks/terraform.tfvars.example
- aws/eks/variables.tf
* Add `eks` module
* Add `eks-backing-services-peering` module
* To provision a complete EKS cluster on AWS with worker nodes and autoscaling group
* To create a peering VPC connection between the EKS cluster and the backing services VPC
> Add `eks` module. Add `eks-backing-services-peering` module

- aws/backing-services/elasticache-redis.tf
- aws/backing-services/elasticsearch.tf
- aws/ecr/kops_ecr_app.tf
* Update various of tf modules
* To get the latest features
> [aws/backing-services] update module versions

- aws/account-settings/main.tf
- aws/account-settings/outputs.tf
- aws/account-settings/variables.tf
- aws/root-iam/root.tf
- aws/users/main.tf
- aws/users/variables.tf
- aws/users/welcome.txt
* Add a `users` module
* Add a `account-settings module
* Make it easy to use GitOps to provision users
> [aws/users,aws/account-settings] new modules

- aws/kops/main.tf
> remove state as hardcoded

- aws/backing-services/aurora-mysql.tf
- aws/backing-services/aurora-postgres.tf
* Add Aurora MySQL module
* Update Aurora Postgres module
* To provision Aurora MySQL clusters
* Availability zones were dropped from https://github.com/cloudposse/terraform-aws-rds-cluster
> Add Aurora MySQL

- aws/ses/Makefile
- aws/ses/emails.tf
- aws/ses/main.tf
* Update descriptions
* Update SES lambda forwarder
* Use remote zip artifacts
> [ses] update lambda forwarder

- aws/tfstate-backend/scripts/delete-bucket.sh
- aws/tfstate-backend/scripts/destroy.sh
- aws/tfstate-backend/scripts/init.sh
* Use `true` and `false` instead of of `0` (for true?)
* Add helper script to delete all object versions and bucket (good for cleaning up messes)
* Using `0` for `true` is weird in this context
> [tfstate-backend] Update scripts to use true/false

- aws/kops/Makefile
- aws/kops/main.tf
- aws/kops/variables.tf
* Use `aws_ssm_parameter` resource directly
* Using module causes "count of" errors during cold start (I didn't learn my lesson)
> [kops] Fix count of errors

- aws/backing-services/rds-replica.tf
- aws/backing-services/rds.tf
* Add rds replica instance support
* For reporting
> [aws/backing-services] Add RDS replica

- aws/backing-services/aurora-mysql.tf
- aws/backing-services/aurora-postgres-replica.tf
- aws/backing-services/aurora-postgres.tf
- aws/backing-services/aurora-replica.tf
* Add RDS aurora replica group
* Reporting database 
* https://github.com/cloudposse/terraform-aws-rds-cluster-instance-group/pull/1
> [aws/backing-services] Add aurora rds replica

- aws/backing-services/vpc.tf
- aws/vpc-peering/Makefile
- aws/vpc-peering/main.tf
- aws/vpc-peering/terraform.tfvars.example
- aws/vpc-peering/variables.tf
* Implement cross-account VPC peering
* Support use-cases where one VPC needs to access another e.g. access the RDS instance in the other VPC
> [vpc-peering] Implement cross-account peering

- aws/vpc-peering/variables.tf
* Correct spelling of `description`
* User error
> [aws/vpc-peering] Fix typo

- .gitignore
- aws/ecs/Makefile
- aws/ecs/README.md
- aws/ecs/acm.tf
- aws/ecs/alb.tf
- aws/ecs/atlantis.tf
- aws/ecs/default-backend.tf
- aws/ecs/ecs.tf
- aws/ecs/main.tf
- aws/ecs/sns.tf
- aws/ecs/variables.tf
- aws/ecs/vpc.tf
* Add ECS cluster with Atlantis Task
* Terraform CI/CD
Closes https://github.com/cloudposse/terraform-root-modules/issues/90
> [ecs] Add fargate cluster with atlantis task

- aws/ecs/acm.auto.tfvars.example
- aws/ecs/acm.tf
- aws/ecs/atlantis.auto.tfvars.example
- aws/ecs/atlantis.tf
- aws/ecs/dns.auto.tfvars.example
- aws/ecs/dns.tf
* Add support for creating a DNS zone for the ECS cluster
* Service discovery
> [aws/ecs] Add support for managed DNS zone

- aws/ecr/kops_ecr_app.tf
- aws/ecr/main.tf
- aws/ecr/terraform.tfvars.example
* Added variable for external participants for ecr
* To grant access to ecr external aws account
> Ecr external participants

- aws/chamber/user.tf
* Allow disabling chamber user
* For some project we do not need to have chamber user
> Allow to disable chamber user

- aws/chamber/user.tf
* Update chamber user
* To fix disabling user
> Update chamber user

- aws/kops-aws-platform/efs-provisioner.tf
Adds EFS provisioning
So we can mount EFS into the Kops cluster
> [aws/kops-aws-platform] add EFS support

- aws/kops-iam-users/Makefile
- aws/kops-iam-users/terraform.tfvars.example
Add Makefile to aws/kops-iam-users/
Required by Atlantis
> [aws/kops-iam-users] Include terraform Makefile and example vars

- aws/kops-aws-platform/efs-provisioner.tf
- aws/kops-aws-platform/iam-authenticator.tf
Disable EFS by default
Not ordinarily needed
> [kops-aws-platform] Default EFS to disabled

- aws/kops-aws-platform/external-dns.tf
- aws/kops-aws-platform/main.tf
- aws/kops-aws-platform/terraform.tfvars.example
- aws/kops-aws-platform/variables.tf
- aws/teleport/Makefile
- aws/teleport/main.tf
- aws/teleport/outputs.tf
- aws/teleport/terraform.tfvars.example
- aws/teleport/variables.tf
Configure backend storage and related roles and secrets for [Teleport](https://gravitational.com/teleport/)
Create resources needed by Teleport
> [Teleport] Add Teleport backend configuration

- aws/codefresh-onprem/main.tf
- aws/kops-aws-platform/alb-ingress.tf
* Added ACM certificate
* For ALB
> Added ACM for codefresh

- aws/kops-aws-platform/iam-authenticator.tf
Update terraform-aws-kops-iam-authenticator-config to current version
Pick up bug fixes
> [kops-aws-platform] Update terraform-aws-kops-iam-authenticator-config

- aws/kops-aws-platform/iam-authenticator.tf
Minor bugfix.
See [terraform-aws-kops-iam-authenticator-config PR 5](https://github.com/cloudposse/terraform-aws-kops-iam-authenticator-config/pull/5)
bugfix
> [kops-aws-platform] iam-authenticator bugfix

- aws/datadog/main.tf
- aws/datadog/variables.tf
Provision a cluster secret for Datadog
See https://github.com/cloudposse/helmfiles/pull/101
> [datadog] Provision a cluster secret

- aws/ecs/default-backend.tf
* [esc/atlantis] Remove unused attribute from `default_backend_web_app`
* Old attribute (forgot to remove)
> [esc/atlantis] Remove unused attribute from `default_backend_web_app`

- aws/tfstate-backend/main.tf
- aws/tfstate-backend/scripts/init.sh
[aws/tfstate-backend] update from version 0.1.1 to version 0.7.0
Enforce server-side encryption and pick up other new features
> [aws/tfstate-backend] update to version 0.7.0

- aws/backing-services/elasticache-redis.tf
- aws/backing-services/main.tf
- aws/backing-services/vpc.tf
* Allow to specify availability zones we'd like to use
* Fix the bug when AWS adds new availability zone
> Fix avilability zone

- aws/backing-services/vpc.tf
* Added tags "type: private" and "type: public" for subnets
* Allow selecting only private subnets with tags
> Subnets tagging

- aws/codefresh-onprem/main.tf
* Fix `elasticache_redis_host` output
* Copy-paste from another output
> Fix `elasticache_redis_host` output

- aws/codefresh-onprem/main.tf
* Allow overriding chamber keys where the secrets saved
* Be flexible to integrate with helmfiles
> [codefresh] Added chamber parameters mapping

- aws/keycloak-backing-services/Makefile
- aws/keycloak-backing-services/aurora-mysql.tf
- aws/keycloak-backing-services/main.tf
Provision Aurora MySQL instance configured for Keycloak
Support Keycloak deployment
> [keycloak-backing-services] Initial implementation

- aws/elasticsearch/Makefile
- aws/elasticsearch/main.tf
- aws/elasticsearch/variables.tf
Standalone module for deploying AWS Elasticsearch 
Support ELK stack
> [elasticsearch] Install Elasticsearch by itself

- README.md
- README.yaml
Update README documentation on "usage"
Reflect revised practice of dynamically updating modules at run time rather than statically including them at build time
> [README] Update documentation on "usage"

- aws/codefresh-onprem/main.tf
* Added backups support
* Added option `postgres_cluster_enabled` to disable PostgreSQL
* Added option `redis_cluster_enabled` to disable Redis 
* To do backups
* Useful for a use case with self-hosted PostgreSQL
* Useful for a use case with self-hosted Redis
> Added codefresh backup

- aws/keycloak-backing-services/README.md
- aws/keycloak-backing-services/aurora-mysql.tf
- aws/keycloak-backing-services/main.tf
[keycloak-backing-services] Minor enhancements such as database deletion protection, proper generation of password. Document security considerations.
Recommended updates after code review.
> [keycloak-backing-services] minor enhancements

- aws/ecs/default-backend.tf
- aws/ecs/flow-logs.tf
* Added `VPC Flow logs`
* To address `CIS Foundation`  requirements
> Vpc flow logs

- aws/elasticsearch/main.tf
- aws/elasticsearch/variables.tf
Save endpoint information in SSM
Avoid copy-paste of information from Terraform output to other configuration files
> [elasticsearch] Save endpoint information in SSM

- aws/backing-services/flow-logs.tf
* Added `VPC Flow logs` for `backing-services`
* To address `CIS Foundation` requirements
> Added flow logs for backing services

- aws/kops-aws-platform/flow-logs.tf
* Added `VPC Flow logs` for `backing-services`
* To address `CIS Foundation` requirements
> Added kops flow logs

- aws/grafana-backing-services/Makefile
- aws/grafana-backing-services/README.md
- aws/grafana-backing-services/aurora-mysql.tf
- aws/grafana-backing-services/main.tf
Provision database for Grafana
Grafana otherwise loses all customization when the pod is destroyed
> Add grafana

- aws/root-dns/parent-alerts-ns.tf
* `alerts` domain added
* for example for SMTP server to be used for alerts notifications
> alerts domain

- aws/vpc/main.tf
* Fix public ip address
* EIP force that flag true
> Fix EIP NAT instances

- aws/dynamodb/Makefile
- aws/dynamodb/dynamodb.tf
- aws/dynamodb/main.tf
- aws/dynamodb/outputs.tf
- aws/dynamodb/ssm.tf
- aws/dynamodb/variables.tf
* Add `dynamodb` module
* To provision a DynamoDB table with optional autoscaling and backup
> Add `dynamodb`

- aws/aws-metrics-role/main.tf
- aws/aws-metrics-role/variables.tf
- aws/elasticsearch/main.tf
- aws/elasticsearch/variables.tf
- aws/kops-aws-platform/alb-ingress.tf
- aws/kops-aws-platform/autoscaler-role.tf
- aws/kops-aws-platform/chart-repo.tf
- aws/kops-aws-platform/efs-provisioner.tf
- aws/kops-aws-platform/external-dns.tf
- aws/kops-aws-platform/iam-authenticator.tf
- aws/kops-aws-platform/variables.tf
- aws/teleport/main.tf
- aws/teleport/variables.tf
* Added IAM role max assume session duration variable
* Allow using KIAM with extended session duration
> Added IAM role session duration

- aws/elasticsearch/main.tf
- aws/elasticsearch/outputs.tf
- aws/elasticsearch/variables.tf
* [elasticsearch] Convert to TF 0.12
* Stay up to date
> [elasticsearch] Convert to TF 0.12

- aws/sentry/rds.tf
* RDS instance postgres added for Sentry backend
* Sentry requires backend DB
> RDS instance postgres added

- aws/github-org-ecr/Makefile
- aws/github-org-ecr/main.tf
- aws/github-org-ecr/terraform.tfvars.example
- aws/github-org-ecr/variables.tf
- aws/github-org-ecr/versions.tf
* module to create `ECR` repo for every `github` repo for given organization
* to automate creation of ECR repos
> module to create ECR repo for every github repo for organization

- aws/github-org-ecr/main.tf
- aws/github-org-ecr/variables.tf
* `ECR` user added
* to allow to push/pull images using AWS credentials or token of this user
> ecr user added

- aws/github-org-ecr/main.tf
- aws/github-org-ecr/variables.tf
* cache_registry_name adde to create ECR registry for caching
* might be useful for example for `codefresh` external cache registry
> cache_registry_name adde to create ECR registry for caching

- modules/account-map/modules/iam-roles/outputs.tf
- modules/account-map/modules/iam-roles/tfstate.tf
- modules/account-map/modules/roles-to-principals/tfstate.tf
- modules/account-settings/providers.tf
- modules/account-settings/tfstate-context.tf
- modules/account/main.tf
- modules/account/outputs.tf
- modules/account/tfstate-context.tf
- modules/account/variables.tf
- modules/cloudtrail-bucket/tfstate-context.tf
- modules/datadog-integration/tfstate-context.tf
- modules/datadog-monitor/tfstate-context.tf
- modules/dns-delegated/outputs.tf
- modules/dns-delegated/tfstate-context.tf
- modules/dns-primary/tfstate-context.tf
- modules/dns-primary/variables.tf
- modules/opsgenie/tfstate-context.tf
- modules/sso/tfstate-context.tf
- modules/tfstate-backend/tfstate-context.tf
- modules/vpc/tfstate-context.tf
* Update `account` component
* Add `organization_enabled` flag
* Allow using an existing Organization instead of creating a new one
> Update `account` component

- modules/elasticache-redis/README.md
- modules/elasticache-redis/context.tf
- modules/elasticache-redis/default.auto.tfvars
- modules/elasticache-redis/main.tf
- modules/elasticache-redis/modules/redis_cluster/context.tf
- modules/elasticache-redis/modules/redis_cluster/main.tf
- modules/elasticache-redis/modules/redis_cluster/outputs.tf
- modules/elasticache-redis/modules/redis_cluster/variables.tf
- modules/elasticache-redis/modules/redis_cluster/versions.tf
- modules/elasticache-redis/outputs.tf
- modules/elasticache-redis/providers.tf
- modules/elasticache-redis/remote-state.tf
- modules/elasticache-redis/variables.tf
- modules/elasticache-redis/versions.tf
* Adds elasticache-redis component
* Keeping our components up-to-date with updates that have been made for clients
> feat: adds elasticache-redis

- modules/github-runners/README.md
- modules/github-runners/context.tf
- modules/github-runners/default.auto.tfvars
- modules/github-runners/iam.tf
- modules/github-runners/main.tf
- modules/github-runners/providers.tf
- modules/github-runners/remote-state.tf
- modules/github-runners/ssm.tf
- modules/github-runners/templates/amazon-cloudwatch-agent.json
- modules/github-runners/templates/user-data.sh
- modules/github-runners/variables.tf
- modules/github-runners/versions.tf
* add `github-runners` component
* Upstream the component to terraform-aws-components to allow others to contribute and allow easier updates in the future
N/A
> feat: add `github-runners` component

- modules/aws-backup/README.md
- modules/aws-backup/context.tf
- modules/aws-backup/default.auto.tfvars
- modules/aws-backup/main.tf
- modules/aws-backup/outputs.tf
- modules/aws-backup/providers.tf
- modules/aws-backup/variables.tf
- modules/aws-backup/versions.tf
* Upstream `aws-backup` component
* Sets up AWS Backup
* https://github.com/cloudposse/terraform-aws-backup/releases/tag/0.8.1
To pass pre-commit hook
```shell
tfenv install 0.13.5
tfenv use 0.13.5
make init
make readme
pre-commit
git add modules/mq-broker
```
> feat: Upstream `aws-backup`

- .github/workflows/pre-commit-check-and-autocommit-changes.yaml
- .pre-commit-config.yaml
* Use cloudposse pre-commit
* Show changes coming from our bot user instead of a non-existent user
* https://github.com/cloudposse/github-action-pre-commit
> Use cloudposse pre-commit

- modules/global-accelerator-endpoint-group/README.md
- modules/global-accelerator-endpoint-group/context.tf
- modules/global-accelerator-endpoint-group/default.auto.tfvars
- modules/global-accelerator-endpoint-group/main.tf
- modules/global-accelerator-endpoint-group/outputs.tf
- modules/global-accelerator-endpoint-group/providers.tf
- modules/global-accelerator-endpoint-group/remote-state.tf
- modules/global-accelerator-endpoint-group/variables.tf
- modules/global-accelerator-endpoint-group/versions.tf
- modules/global-accelerator/README.md
- modules/global-accelerator/context.tf
- modules/global-accelerator/default.auto.tfvars
- modules/global-accelerator/main.tf
- modules/global-accelerator/outputs.tf
- modules/global-accelerator/providers.tf
- modules/global-accelerator/variables.tf
- modules/global-accelerator/versions.tf
* Add global accelerator
* Upstream
N/A
> Add global accelerator

- modules/opsgenie-team/README.md
- modules/opsgenie-team/context.tf
- modules/opsgenie-team/default.auto.tfvars
- modules/opsgenie-team/introspection.mixin.tf
- modules/opsgenie-team/main.tf
- modules/opsgenie-team/modules/escalations/README.md
- modules/opsgenie-team/modules/escalations/context.tf
- modules/opsgenie-team/modules/escalations/main.tf
- modules/opsgenie-team/modules/escalations/outputs.tf
- modules/opsgenie-team/modules/escalations/variables.tf
- modules/opsgenie-team/modules/escalations/versions.tf
- modules/opsgenie-team/modules/integration/context.tf
- modules/opsgenie-team/modules/integration/main.tf
- modules/opsgenie-team/modules/integration/outputs.tf
- modules/opsgenie-team/modules/integration/variables.tf
- modules/opsgenie-team/modules/integration/versions.tf
- modules/opsgenie-team/modules/routing/context.tf
- modules/opsgenie-team/modules/routing/main.tf
- modules/opsgenie-team/modules/routing/outputs.tf
- modules/opsgenie-team/modules/routing/variables.tf
- modules/opsgenie-team/modules/routing/versions.tf
- modules/opsgenie-team/outputs.tf
- modules/opsgenie-team/providers.tf
- modules/opsgenie-team/ssm.tf
- modules/opsgenie-team/variables.tf
- modules/opsgenie-team/versions.tf
* A Component that manages an opsgenie team and its corresponding resources
* The OpsGenie Team is a core component that needs many backing resources spun up. This creates those sane defaults
> feat: upstream `opsgenie-team`

- .github/auto-release.yml
- .github/workflows/auto-release.yml
- .gitignore
- Update .gitignore to current
- Update auto-release workflow to current
- Previous versions were lacking features/content
> Update .gitignore to current

- .pre-commit-config.yaml
* Bump pre-commit and use https
* Fix error https://github.com/cloudposse/terraform-aws-components/runs/6181594993?check_suite_focus=true
N/A
> Bump pre-commit and use https

- modules/datadog-agent/README.md
- modules/datadog-agent/catalog/cluster-checks/defaults/http_checks.yaml
- modules/datadog-agent/catalog/cluster-checks/dev/http_checks.yaml
- modules/datadog-agent/default.auto.tfvars
- modules/datadog-agent/helm-variables.tf
- modules/datadog-agent/introspection.mixin.tf
- modules/datadog-agent/main.tf
- modules/datadog-agent/outputs.tf
- modules/datadog-agent/provider-helm.tf
- modules/datadog-agent/providers.tf
- modules/datadog-agent/remote-state.tf
- modules/datadog-agent/variables.tf
- modules/datadog-agent/versions.tf
* Includes methodology for HTTP Cluster Checks
* HTTP Checks are easy and lighter (cheaper too) than synthetics
* N/A
> Feat: Update `datadog-agent` component

- modules/tfstate-backend/README.md
- modules/tfstate-backend/context.tf
- modules/tfstate-backend/default.auto.tfvars
- modules/tfstate-backend/introspection.mixin.tf
- modules/tfstate-backend/main.tf
- modules/tfstate-backend/variables.tf
- modules/tfstate-backend/versions.tf
* Updates to latest
* Consistency and new vendoring
> Upgrade Component: `tfstate-backend`

- modules/vpc/README.md
- modules/vpc/context.tf
- modules/vpc/default.auto.tfvars
- modules/vpc/main.tf
- modules/vpc/outputs.tf
- modules/vpc/providers.tf
- modules/vpc/remote-state.tf
- modules/vpc/variables.tf
- modules/vpc/versions.tf
- modules/vpc/vpc-flow-logs.tf
* Upstreams VPC Component
* Upstreams
> `[VPC]` Upstream

- modules/ec2-client-vpn/README.md
- modules/ec2-client-vpn/context.tf
- modules/ec2-client-vpn/default.auto.tfvars
- modules/ec2-client-vpn/main.tf
- modules/ec2-client-vpn/outputs.tf
- modules/ec2-client-vpn/providers.tf
- modules/ec2-client-vpn/remote-state.tf
- modules/ec2-client-vpn/variables.tf
- modules/ec2-client-vpn/versions.tf
* upstreams ec2 client vpn
* Upstream core component
* N/A
> `ec2-client-vpn` upstream

- modules/aurora-postgres-resources/README.md
- modules/aurora-postgres-resources/additional-databases.tf
- modules/aurora-postgres-resources/additional-users.tf
- modules/aurora-postgres-resources/context.tf
- modules/aurora-postgres-resources/default.auto.tfvars
- modules/aurora-postgres-resources/main.tf
- modules/aurora-postgres-resources/modules/postgresql-user/context.tf
- modules/aurora-postgres-resources/modules/postgresql-user/main.tf
- modules/aurora-postgres-resources/modules/postgresql-user/outputs.tf
- modules/aurora-postgres-resources/modules/postgresql-user/variables.tf
- modules/aurora-postgres-resources/modules/postgresql-user/versions.tf
- modules/aurora-postgres-resources/outputs.tf
- modules/aurora-postgres-resources/providers.tf
- modules/aurora-postgres-resources/read-only-user.tf
- modules/aurora-postgres-resources/remote-state.tf
- modules/aurora-postgres-resources/variables.tf
- modules/aurora-postgres-resources/versions.tf
* Upstream aurora-postgres-resources
* Clients can take advantage of upstream fixes
N/A
> Upstream aurora-postgres-resources

- modules/documentdb/README.md
- modules/documentdb/context.tf
- modules/documentdb/default.auto.tfvars
- modules/documentdb/main.tf
- modules/documentdb/outputs.tf
- modules/documentdb/providers.tf
- modules/documentdb/remote-state.tf
- modules/documentdb/ssm.tf
- modules/documentdb/variables.tf
- modules/documentdb/versions.tf
* Add `documentdb` component
* This component can be used to provision DocumentDB clusters.
* N/A
> Feat: upstream `documentdb` component

- modules/dns-delegated/README.md
- modules/dns-delegated/acm.tf
- modules/dns-delegated/context.tf
- modules/dns-delegated/default.auto.tfvars
- modules/dns-delegated/main.tf
- modules/dns-delegated/outputs.tf
- modules/dns-delegated/providers.tf
- modules/dns-delegated/remote-state.tf
- modules/dns-delegated/variables.tf
- modules/dns-delegated/versions.tf
* Upstreams DNS Delegated
* Recent bugfix in spacelift that need default `aws` provider
> upstreaming `dns-delegated`

- modules/dns-primary/README.md
- modules/dns-primary/acm.tf
- modules/dns-primary/context.tf
- modules/dns-primary/default.auto.tfvars
- modules/dns-primary/main.tf
- modules/dns-primary/outputs.tf
- modules/dns-primary/providers.tf
- modules/dns-primary/variables.tf
- modules/dns-primary/versions.tf
* Upstreams DNS Primary 
* Providing component updates
> upstream `dns-primary`

- modules/spacelift-worker-pool/README.md
- modules/spacelift-worker-pool/context.tf
- modules/spacelift-worker-pool/data.tf
- modules/spacelift-worker-pool/default.auto.tfvars
- modules/spacelift-worker-pool/iam.tf
- modules/spacelift-worker-pool/main.tf
- modules/spacelift-worker-pool/outputs.tf
- modules/spacelift-worker-pool/providers.tf
- modules/spacelift-worker-pool/remote-state.tf
- modules/spacelift-worker-pool/templates/spacelift@.service
- modules/spacelift-worker-pool/templates/user-data.sh
- modules/spacelift-worker-pool/variables.tf
- modules/spacelift-worker-pool/versions.tf
- Upstream `spacelift-worker-pool` from CPLIVE
- This component is required downstream, and we would like to pull via vendoring
- N/A
> Upstream `spacelift-worker-pool`

- modules/global-accelerator-endpoint-group/README.md
- modules/global-accelerator-endpoint-group/context.tf
- modules/global-accelerator-endpoint-group/main.tf
- modules/global-accelerator-endpoint-group/providers.tf
- modules/global-accelerator-endpoint-group/remote-state.tf
- modules/global-accelerator-endpoint-group/versions.tf
- modules/global-accelerator/README.md
- modules/global-accelerator/context.tf
- modules/global-accelerator/main.tf
- modules/global-accelerator/providers.tf
- modules/global-accelerator/remote-state.tf
- modules/global-accelerator/variables.tf
- modules/global-accelerator/versions.tf
- Upstream `global-accelerator` and `global-accelerator-endpoint-group`
- Updating the upstream components
* N/A
> Upstream AWS Global Accelerator Components

- modules/lakeformation/README.md
- modules/lakeformation/context.tf
- modules/lakeformation/default.auto.tfvars
- modules/lakeformation/main.tf
- modules/lakeformation/outputs.tf
- modules/lakeformation/providers.tf
- modules/lakeformation/variables.tf
- modules/lakeformation/versions.tf
* New 'lakeformation' component to deploy Amazon Lake formation resources in AWS, w/ docs and sample config
> Adding new 'lakeformation' component

- modules/github-runners/README.md
- modules/github-runners/iam.tf
- modules/github-runners/main.tf
- modules/github-runners/modules/graceful_scale_in/ssm.tf
- modules/github-runners/remote-state.tf
- modules/github-runners/ssm.tf
- modules/github-runners/templates/create-latest-svc.sh
- modules/github-runners/templates/user-data.sh
- modules/github-runners/variables.tf
* Github runner fixes
* Upstream latest
N/A
> Github runner fixes

- modules/github-action-token-rotator/README.md
- modules/github-action-token-rotator/context.tf
- modules/github-action-token-rotator/default.auto.tfvars
- modules/github-action-token-rotator/main.tf
- modules/github-action-token-rotator/outputs.tf
- modules/github-action-token-rotator/providers.tf
- modules/github-action-token-rotator/variables.tf
- modules/github-action-token-rotator/versions.tf
* Add github-action-token-rotator
* Rotate github app token for better security posture
- https://github.com/cloudposse/terraform-aws-github-action-token-rotator
> Add github-action-token-rotator

- modules/kinesis-stream/README.md
- modules/kinesis-stream/context.tf
- modules/kinesis-stream/default.auto.tfvars
- modules/kinesis-stream/main.tf
- modules/kinesis-stream/outputs.tf
- modules/kinesis-stream/providers.tf
- modules/kinesis-stream/variables.tf
- modules/kinesis-stream/versions.tf
* Adding new `kinesis-stream` component w/ documentation
> Adding new kinesis-stream component

- modules/datadog-lambda-forwarder/README.md
- modules/datadog-lambda-forwarder/context.tf
- modules/datadog-lambda-forwarder/default.auto.tfvars
- modules/datadog-lambda-forwarder/main.tf
- modules/datadog-lambda-forwarder/outputs.tf
- modules/datadog-lambda-forwarder/providers.tf
- modules/datadog-lambda-forwarder/variables.tf
- modules/datadog-lambda-forwarder/versions.tf
* Add datadog-lambda-forwarder
* Upstream
N/A
> Add datadog-lambda-forwarder

- modules/ecs-service/README.md
- modules/ecs-service/context.tf
- modules/ecs-service/main.tf
- modules/ecs-service/outputs.tf
- modules/ecs-service/providers.tf
- modules/ecs-service/remote-state.tf
- modules/ecs-service/variables.tf
- modules/ecs-service/versions.tf
* Upstream ecs-service
* Upstream new component
- DEV-258
* Similar PR https://github.com/cloudposse/terraform-aws-components/pull/461
> Upstream ecs-service

- modules/kms/README.md
- modules/kms/context.tf
- modules/kms/main.tf
- modules/kms/outputs.tf
- modules/kms/providers.tf
- modules/kms/variables.tf
- modules/kms/versions.tf
* Simple KMS Component
* Upstream
> upstream `kms`

- modules/mwaa/README.md
- modules/mwaa/context.tf
- modules/mwaa/iam.tf
- modules/mwaa/main.tf
- modules/mwaa/outputs.tf
- modules/mwaa/providers.tf
- modules/mwaa/remote-state.tf
- modules/mwaa/variables.tf
- modules/mwaa/versions.tf
* Adding new `mwaa` component for Amazon Airflow deployments
> Adding new 'mwaa' component

- modules/cognito/README.md
- modules/cognito/client.tf
- modules/cognito/context.tf
- modules/cognito/default.auto.tfvars
- modules/cognito/domain.tf
- modules/cognito/identity-provider.tf
- modules/cognito/main.tf
- modules/cognito/outputs.tf
- modules/cognito/providers.tf
- modules/cognito/resource-server.tf
- modules/cognito/user-group.tf
- modules/cognito/variables.tf
- modules/cognito/versions.tf
* AWS Cognito Component
* Upstream
> `cognito` component

- modules/kinesis-stream/README.md
- modules/kinesis-stream/main.tf
* Bumping version of `kinesis-stream` upstream module to `0.3.0` to resolve issues with certain configurations
> Bumping version of kinesis-stream module to 0.3.0

- modules/cognito/README.md
> `cognito` readme cleanup

- modules/eks/echo-server/README.md
- modules/eks/echo-server/charts/echo-server/templates/ingress.yaml
- modules/eks/echo-server/charts/echo-server/values.yaml
- modules/eks/echo-server/main.tf
- modules/eks/echo-server/remote-state.tf
- modules/eks/echo-server/variables.tf
* Echo server upstream
* ALB Group support
* ALB Logging support
* Upstream
* Better test of all our featuresets
> upstream `echo-server` with alb group and logging

- .github/workflows/bats.yml
- modules/github-runners/README.md
- modules/github-runners/remote-state.tf
- modules/github-runners/variables.tf
- modules/github-runners/versions.tf
- Minor TLC updates for GitHub Runners ASG component
- Maintaining up-to-date upstream
> Upstream `github-runners`

- modules/iam-service-linked-roles/README.md
- modules/iam-service-linked-roles/context.tf
- modules/iam-service-linked-roles/main.tf
- modules/iam-service-linked-roles/outputs.tf
- modules/iam-service-linked-roles/providers.tf
- modules/iam-service-linked-roles/variables.tf
- modules/iam-service-linked-roles/versions.tf
* Upstream iam-service-linked-roles (thanks to @aknysh for writing it)
* Centralized component to create IAM service linked roles
- N/A
> Upstream iam-service-linked-roles

- modules/account-map/modules/iam-roles/outputs.tf
- modules/account-map/modules/iam-roles/variables.tf
- modules/vpc-peering/README.md
- modules/vpc-peering/default.auto.tfvars
- modules/vpc-peering/main.tf
- modules/vpc-peering/providers.tf
- modules/vpc-peering/remote-state.tf
- modules/vpc-peering/variables.tf
* Allow vpc-peering to peer v2 to v2
* Alternative to transit gateway
N/A
> Allow vpc-peering to peer v2 to v2

- modules/eks/metrics-server/README.md
- modules/eks/metrics-server/versions.tf
* Pin the k8s provider version
* Update versions 
* Fix CI
* https://github.com/cloudposse/terraform-aws-components/pull/537
> Pin kubernetes provider in metrics-server

- modules/datadog-agent/README.md
- modules/datadog-agent/main.tf
- modules/datadog-agent/outputs.tf
- modules/datadog-agent/variables.tf
- modules/datadog-agent/versions.tf
* Allows values to be passed in and merged to values file
* Need to be able to easily override values files
> `datadog-agent` allow values var merged

- README.md
- modules/datadog-agent/README.md
- modules/eks/external-dns/README.md
- modules/eks/external-dns/variables.tf
- modules/zscaler/README.md
* Fixed non-html tags
* Rendering has been failing on docusaurus mdx/jsx engine
> Fixed non-html tags that fails rendering on docusaurus

- modules/lambda/README.md
- modules/lambda/context.tf
- modules/lambda/lambdas/.gitignore
- modules/lambda/lambdas/hello-world-go/Makefile
- modules/lambda/lambdas/hello-world-go/go.mod
- modules/lambda/lambdas/hello-world-go/hello_world.go
- modules/lambda/main.tf
- modules/lambda/outputs.tf
- modules/lambda/providers.tf
- modules/lambda/variables.tf
- modules/lambda/versions.tf
* Upstream `lambda` component
* Quickly deploy serverless code
> upstream `lambda`

- modules/aws-backup/README.md
- modules/aws-backup/context.tf
- modules/aws-backup/default.auto.tfvars
- modules/aws-backup/main.tf
- modules/aws-backup/outputs.tf
- modules/aws-backup/providers.tf
- modules/aws-backup/variables.tf
- modules/aws-backup/versions.tf
* Update `aws-backup` to latest
> `aws-backup` upstream

- modules/datadog-agent/README.md
* Update Datadog Docs to be more clear on catalog entry
> update dd agent docs

- modules/redshift/README.md
- modules/redshift/context.tf
- modules/redshift/main.tf
- modules/redshift/outputs.tf
- modules/redshift/providers.tf
- modules/redshift/remote-state.tf
- modules/redshift/systems-manager.tf
- modules/redshift/variables.tf
- modules/redshift/versions.tf
* Add Redshift
* Fulfilling the AWS catalog
* https://github.com/cloudposse/terraform-aws-redshift-cluster
> Add Redshift component

- modules/argocd-repo/templates/applicationset.yaml.tpl
- modules/eks/argocd/README.md
- modules/eks/argocd/main.tf
* Fix slack notification annotations 
* Fix CRD creation order
* Fix ArgoCD bootstrap
> Fix ArgoCD minor issues

- modules/account-map/README.md
- modules/account-map/modules/iam-roles/main.tf
- modules/account-map/remote-state.tf
- modules/account-map/versions.tf
* Update remote config module version `1.4.1`
* Solve terraform module version conflict
> [account-map] Update remote config module version

- modules/eks/argocd/README.md
- modules/eks/argocd/main.tf
- modules/eks/argocd/resources/argocd-values.yaml.tpl
- modules/eks/argocd/variables-argocd.tf
> ArgoCD SSO improvements

- modules/argocd-repo/templates/applicationset.yaml.tpl
* Added ArgoCD GitHub notification subscription
* To use synchronous deployment pattern
> Added ArgoCD GitHub notification subscription

- modules/eks/cluster/README.md
- Updated the README with EKS cluster
The example stack is outdated. Add notes for Github OIDC and karpenter
https://cloudposse.atlassian.net/browse/DEV-835
> Update `eks/cluster` README

- modules/aws-sso/README.md
- modules/aws-sso/main.tf
* upgrade aws-sso modules: permission_sets, sso_account_assignments, and
sso_account_assignments_root
* upstream updates
> chore: aws-sso modules updated to 1.0.0

- modules/s3-bucket/README.md
- modules/s3-bucket/main.tf
- modules/s3-bucket/versions.tf
* use cloud posse's template provider
* arm64
* also this provider was not pinned in versions.tf so that had to be fixed somehow
* closes #617
> s3-bucket: use cloudposse template provider for arm64

- modules/argocd-repo/templates/applicationset.yaml.tpl
* [argocd-repo] Added ArgoCD git commit notifications
* ArgoCD sync deployment
> [argocd-repo] Added ArgoCD git commit notifications

- modules/github-oidc-provider/README.md
Added common question for GHA
This is asked frequently
https://cloudposse.slack.com/archives/C04N39YPVAS/p1682355553255269
> GitHub OIDC FAQ

- modules/eks/datadog-agent/README.md
- modules/eks/datadog-agent/main.tf
* update datadog agent to latest
* remove variable in datadog configuration
> `datadog-agent` bugfixes

- modules/aws-inspector/README.md
- modules/aws-inspector/context.tf
- modules/aws-inspector/main.tf
- modules/aws-inspector/outputs.tf
- modules/aws-inspector/providers.tf
- modules/aws-inspector/variables.tf
- modules/aws-inspector/versions.tf
Upstream `aws-inspector` from past engagement
* This component was never upstreamed and now were want to use it again
* AWS Inspector is a security assessment service offered by Amazon Web Services (AWS). It helps you analyze and evaluate the security and compliance of your applications and infrastructure deployed on AWS. AWS Inspector automatically assesses the resources within your AWS environment, such as Amazon EC2 instances, for potential security vulnerabilities and deviations from security best practices. Here are some key features and functionalities of AWS Inspector:
- Security Assessments: AWS Inspector performs security assessments by analyzing the behavior of your resources and identifying potential security vulnerabilities. It examines the network configuration, operating …
> Upstream `aws-inspector`

- README.md
- README.yaml
* Removed list of components from main README.md
* That list is outdated
> Removed list of components from main README.md

- modules/account-map/README.md
- modules/acm/README.md
- modules/datadog-monitor/README.md
- modules/datadog-synthetics/README.md
- modules/dns-primary/README.md
- modules/eks/eks-without-spotinst/README.md
- modules/eks/external-secrets-operator/README.md
- modules/github-oidc-provider/README.md
- modules/opsgenie-team/README.md
- modules/opsgenie-team/modules/escalation/README.md
* Fixed broken links in READMEs
* Fixed broken links in READMEs
* https://github.com/cloudposse/terraform-aws-components/issues/747
> Fixed broken links in READMEs

- modules/eks/eks-without-spotinst/modules/node_group_by_az/main.tf
* Use the new subnets data source
* Planned migration according to https://github.com/hashicorp/terraform-provider-aws/pull/18803
> Use the new subnets data source

- modules/acm/README.md
- modules/acm/main.tf
- modules/acm/outputs.tf
- modules/acm/remote-state.tf
- modules/acm/variables.tf
- modules/acm/versions.tf
* Upstream ACM
* New Variables
* `subject_alternative_names_prefixes`
* `domain_name_prefix`
> `acm` Upstream

- modules/ecs/README.md
- modules/ecs/main.tf
* Update ECS cluster module
* Maintenance
> Bump ECS cluster module

- modules/eks/argocd/README.md
- modules/eks/argocd/data.tf
- modules/eks/argocd/main.tf
- modules/eks/argocd/outputs.tf
- modules/eks/argocd/providers.tf
- modules/eks/argocd/remote-state.tf
- modules/eks/argocd/variables-argocd-notifications.tf
- modules/eks/argocd/variables-argocd.tf
* Restore ssm configuration options for argocd notifications
* notifications were not firing and tasks time out in some installations
> fix: restore notifications config in argocd

- modules/api-gateway-account-settings/README.md
- modules/api-gateway-account-settings/context.tf
- modules/api-gateway-account-settings/main.tf
- modules/api-gateway-account-settings/outputs.tf
- modules/api-gateway-account-settings/providers.tf
- modules/api-gateway-account-settings/variables.tf
- modules/api-gateway-account-settings/versions.tf
- modules/api-gateway-rest-api/README.md
- modules/api-gateway-rest-api/context.tf
- modules/api-gateway-rest-api/main.tf
- modules/api-gateway-rest-api/nlb.tf
- modules/api-gateway-rest-api/outputs.tf
- modules/api-gateway-rest-api/providers.tf
- modules/api-gateway-rest-api/remote-state.tf
- modules/api-gateway-rest-api/variables.tf
- modules/api-gateway-rest-api/versions.tf
* Upstream api-gateway and it's corresponding settings component
> upstream `api-gateway` and `api-gateway-settings`

- docs/upgrade-guide.md
- Set the version to the correct updated release
- Needs to match correct version
#804
> Update upgrade-guide.md Version

- modules/eks/keda/README.md
- modules/eks/keda/context.tf
- modules/eks/keda/main.tf
- modules/eks/keda/outputs.tf
- modules/eks/keda/provider-helm.tf
- modules/eks/keda/providers.tf
- modules/eks/keda/remote-state.tf
- modules/eks/keda/variables.tf
- modules/eks/keda/versions.tf
- Added the component `eks/keda`
- We've deployed KEDA for a few customers now and the component should be upstreamed
- n/a
> Upstream `eks/keda`

- modules/eks/cluster/CHANGELOG.md
- modules/tgw/CHANGELOG.md
- moved changelog for individual components
- changed title
- Title changelogs consistently by components version
- Separate changes by affected components
- https://github.com/cloudposse/knowledge-base/discussions/132
> Refactor Changelog

- modules/api-gateway-rest-api/README.md
* Updated the title
* It was an extra helping of copy/pasta
> Update api-gateway-account-settings README.md

- modules/spacelift/worker-pool/README.md
- modules/spacelift/worker-pool/providers.tf
- Update relative path to `account-map` in `spacelift/worker-pool/providers.tf`
- Fixes #828
> [spacelift/worker-pool] Update providers.tf nesting

- modules/account-settings/README.md
- add an example of notifications to the account-settings component
- improved documentation
> docs: add notifications to account-settings readme

- modules/opsgenie-team/README.md
* Update README.md for `opsgenie-team` component.
* explain plan requirements for component
* provide curl command for evaluating api key
> docs: opsgenie-team plan requirements

- modules/eks/argocd/README.md
Add troubleshooting section for ArgoCD
Addressing repeating customer's issues
> Propose troubleshooting section for ArgoCD

- modules/datadog-monitor/catalog/monitors/lambda-log-forwarder.yaml
Follow up to https://github.com/cloudposse/terraform-aws-components/pull/887
> All DD monitor names must be namespaced

- modules/github-runners/README.md
-  Moving docs from refarch setup to component readme.
- Docs better fit on this component as we move to Philips lab module.
> Component: `github-runners` update readme

- modules/tgw/spoke/remote-state.tf
Fix a bug I introduced when upstreaming because I forgot to include a for-each value
> bug(tgw): fix bug with upstreaming

- modules/alb/README.md
- modules/alb/main.tf
- Upgraded the `alb` module version in the `alb` component
- Use our latest module with the component
- n/a
> chore: bumped `alb` module version

- .github/workflows/update-changelog.yml
* Pin peter-evans/create-pull-request v6
* Update node 20
* https://cloudposse.atlassian.net/browse/DEV-1726
> Pin peter-evans/create-pull-request v6

- modules/datadog-monitor/README.md
- modules/datadog-monitor/catalog/monitors/aurora.yaml
- modules/datadog-monitor/catalog/monitors/ec2.yaml
- modules/datadog-monitor/catalog/monitors/efs.yaml
- modules/datadog-monitor/catalog/monitors/elb.yaml
- modules/datadog-monitor/catalog/monitors/host.yaml
- modules/datadog-monitor/catalog/monitors/k8s.yaml
- modules/datadog-monitor/catalog/monitors/lambda-log-forwarder.yaml
- modules/datadog-monitor/catalog/monitors/lambda.yaml
- modules/datadog-monitor/catalog/monitors/rabbitmq.yaml
- modules/datadog-monitor/catalog/monitors/rds.yaml
- modules/datadog-monitor/main.tf
- update monitor module in datadog-monitor component
- update readme for datadog-monitor
- changed to support importing monitors
> chore: update module in datadog-monitor

- modules/datadog-private-location-ecs/main.tf
- modules/datadog-private-location-ecs/remote-state.tf
update remote state to ecs/cluster and main to support enabled false (and fix issue with count)
> Bugfix: ecs private locations for datadog

- modules/eks/keda/README.md
- modules/eks/keda/main.tf
- modules/eks/keda/variables.tf
- Update keda chart to latest version
- Update resources to be any type
- Only override default resources if something is passed in.
- This chart has a different resources than normal charts.
- https://github.com/kedacore/charts/blob/main/keda/values.yaml#L481-L505
> Update Keda default chart

- .github/workflows/release-published.yml
- Update workflow (`.github/workflows/release.yaml`) to have permissions commenting PR
- Add comments to PRs when it's changes are released
> Update release workflow

- modules/dynamodb/README.md
- modules/dynamodb/outputs.tf
* Add `hash_key` and `range_key` outputs
* Hash and range key are needed by other resources so we should add them as outputs to this component
> Extra Dynamodb outputs

- modules/ec2-client-vpn/README.md
- modules/ecs-service/docs/ecs-partial-task-definitions.md
- Fix formatting in READMEs for docusarus rendering
- Fix closing tags and alignment for MDX
- https://github.com/cloudposse/docs/pull/626
> Fix README Format

- modules/account/README.md
- modules/aws-backup/README.md
- modules/datadog-monitor/README.md
- modules/ecr/README.md
- modules/eks/cluster/README.md
- modules/eks/external-secrets-operator/README.md
- modules/opsgenie-team/README.md
- Updated all links for docs.cloudposse.com
- New version of the docs has been released! As such, there are many changes in links
- DEV-2439
> DEV-2439: Update all docs.cloudposse links

- modules/vpc-peering/main.tf
- modules/vpc-peering/remote-state.tf
> make requester vpc lookup optional if vpc is passed

- modules/runs-on/README.md
- modules/runs-on/context.tf
- modules/runs-on/main.tf
- modules/runs-on/outputs.tf
- modules/runs-on/providers.tf
- modules/runs-on/remote-state.tf
- modules/runs-on/variables.tf
- modules/runs-on/versions.tf
- RunsOn Component and how to setup TGW Connnections
- RunsOn simplifies the Github Action Runner setup
> Upstream `RunsOn`

- modules/runs-on/README.md
- Update frontmatter in runs-on module
- Correct tags
- https://github.com/cloudposse/docs/actions/runs/11278466395/job/31366989761
> fix: Frontmatter for `run-ons`

- modules/eks/spacelift-worker-pool-controller/README.md
- modules/eks/spacelift-worker-pool-controller/context.tf
- modules/eks/spacelift-worker-pool-controller/main.tf
- modules/eks/spacelift-worker-pool-controller/outputs.tf
- modules/eks/spacelift-worker-pool-controller/provider-helm.tf
- modules/eks/spacelift-worker-pool-controller/providers.tf
- modules/eks/spacelift-worker-pool-controller/remote-state.tf
- modules/eks/spacelift-worker-pool-controller/variables.tf
- modules/eks/spacelift-worker-pool-controller/versions.tf
- modules/eks/spacelift-worker-pool/README.md
- modules/eks/spacelift-worker-pool/context.tf
- modules/eks/spacelift-worker-pool/iam.tf
- modules/eks/spacelift-worker-pool/k8s.tf
- modules/eks/spacelift-worker-pool/main.tf
- modules/eks/spacelift-worker-pool/outputs.tf
- modules/eks/spacelift-worker-pool/provider-helm.tf
- modules/eks/spacelift-worker-pool/provider-spacelift.tf
- modules/eks/spacelift-worker-pool/providers.tf
- modules/eks/spacelift-worker-pool/remote-state.tf
- modules/eks/spacelift-worker-pool/variables.tf
- modules/eks/spacelift-worker-pool/versions.tf
- [eks/spacelift-worker-pool] Initial commit
- [eks/spacelift-worker-pool-controller] Initial commit
- Support deployment of the [Kubernetes Operator](https://docs.spacelift.io/concepts/worker-pools/kubernetes-workers) for [Spacelift Worker Pools](https://docs.spacelift.io/concepts/worker-pools#kubernetes) to an EKS cluster
> [eks/spacelift-worker-pool], [eks/spacelift-worker-pool-controller] Initial commit

- README.yaml
* Announce code freeze on readme
* Readme is more informative than issue (while issue will be emailed)
* https://github.com/cloudposse/terraform-aws-components/issues/1177
> Announce code freeze

- README.yaml
* Codefreeze warning update
* Started codefreeze
* https://github.com/cloudposse/terraform-aws-components/issues/1177
> Codefreeze warning update

- .github/mergify.yml
* Enable mergify
* Support code freeze mergify rules
* https://github.com/cloudposse/terraform-aws-components/issues/1177
> Enable mergify

- README.md
- README.yaml
- docs/targets.md
> Migration Done
